import { afterEach, beforeEach, expect, it, spyOn } from "bun:test";
import { act, cleanup, renderHook, waitFor } from "@testing-library/react";
import { IDBFactory } from "fake-indexeddb";
import * as Storage from "@/lib/articles/articleDraftStorage";
import type { ArticleDraft } from "@/lib/articles/articleDraftTypes";
import { useArticleDrafts } from "@/hooks/articles/useArticleDrafts";
const alice = "did:plc:alice";
const bob = "did:plc:bob";
const originalIDB = Object.getOwnPropertyDescriptor(globalThis, "indexedDB");
const restores: (() => void)[] = [];
function deferred<T>() { let resolve!: (value: T) => void; let reject!: (error: Error) => void; const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no; }); return { promise, resolve, reject }; }
function draft(id: string): ArticleDraft { return { id, title: id, markdown: "Original", excerpt: "", path: id, tags: [], publicationUri: "", createdAt: "2026-10-10T00:00:00Z", updatedAt: "2026-10-10T00:00:00Z" }; }
beforeEach(() => Object.defineProperty(globalThis, "indexedDB", { configurable: true, value: new IDBFactory() }));
afterEach(async () => { cleanup(); await new Promise(resolve => setTimeout(resolve, 0)); restores.splice(0).reverse().forEach(restore => restore()); if (originalIDB) Object.defineProperty(globalThis, "indexedDB", originalIDB); else Reflect.deleteProperty(globalThis, "indexedDB"); });
it("serializes private saves and advances revisions without losing newer edits", async () => {
  await Storage.saveArticleDraft(alice, draft("one"));
  const { result } = renderHook(() => useArticleDrafts(alice));
  await waitFor(() => expect(result.current.loading).toBe(false));
  act(() => result.current.update({ markdown: "First edit" }));
  const first = result.current.persist();
  act(() => result.current.update({ markdown: "Latest edit" }));
  await act(async () => { await Promise.all([first, result.current.persist()]); });
  expect((await Storage.getArticleDraft(alice, "one"))!.markdown).toBe("Latest edit");
  expect(result.current.draft!.markdown).toBe("Latest edit");
  expect(result.current.draft!.revision).toBe(3);
});
it("a concurrent selection cannot discard edits when the pending save fails", async () => {
  await Storage.saveArticleDraft(alice, draft("one"));
  await Storage.saveArticleDraft(alice, draft("two"));
  const { result } = renderHook(() => useArticleDrafts(alice));
  await waitFor(() => expect(result.current.loading).toBe(false));
  const originalId = result.current.draft!.id;
  const otherId = originalId === "one" ? "two" : "one";
  const gate = deferred<ArticleDraft>();
  const save = spyOn(Storage, "saveArticleDraft").mockReturnValue(gate.promise); restores.push(() => save.mockRestore());
  act(() => result.current.update({ markdown: "Unsaved private edits" }));
  let writeError: unknown; let selectionError: unknown;
  const writing = result.current.persist().catch(error => { writeError = error; });
  const selecting = result.current.select(otherId).catch(error => { selectionError = error; });
  await act(async () => { gate.reject(new Error("Quota exceeded")); await Promise.all([writing, selecting]); });
  expect(writeError).toBeDefined();
  expect(selectionError).toBeDefined();
  expect(result.current.draft!.id).toBe(originalId);
  expect(result.current.draft!.markdown).toBe("Unsaved private edits");
  expect(result.current.error).toBe("Quota exceeded");
});
it("a late selection response cannot replace a newer selection", async () => {
  const one = await Storage.saveArticleDraft(alice, draft("one"));
  const two = await Storage.saveArticleDraft(alice, draft("two"));
  const { result } = renderHook(() => useArticleDrafts(alice));
  await waitFor(() => expect(result.current.loading).toBe(false));
  const slow = deferred<ArticleDraft | undefined>();
  const fast = deferred<ArticleDraft | undefined>();
  const get = spyOn(Storage, "getArticleDraft").mockImplementation((_did, id) => id === "one" ? slow.promise : fast.promise); restores.push(() => get.mockRestore());
  const first = result.current.select("one");
  const second = result.current.select("two");
  await act(async () => { fast.resolve(two); await second; slow.resolve(one); await first; });
  expect(result.current.draft!.id).toBe("two");
});
it("changing viewers clears another account's selected draft while the new list loads", async () => {
  await Storage.saveArticleDraft(alice, draft("private-alice"));
  const { result, rerender } = renderHook(({ did }) => useArticleDrafts(did), { initialProps: { did: alice } });
  await waitFor(() => expect(result.current.loading).toBe(false));
  const originalList = Storage.listArticleDrafts;
  const pendingBob = deferred<ArticleDraft[]>();
  const lists = spyOn(Storage, "listArticleDrafts").mockImplementation(did => did === bob ? pendingBob.promise : originalList(did)); restores.push(() => lists.mockRestore());
  rerender({ did: bob });
  expect(result.current.draft === undefined).toBe(true);
  expect(result.current.drafts.length).toBe(0);
  await act(async () => pendingBob.resolve([]));
});
it("an initial load that finishes after create cannot replace the new draft", async () => {
  const initial = deferred<ArticleDraft[]>();
  const lists = spyOn(Storage, "listArticleDrafts").mockReturnValue(initial.promise); restores.push(() => lists.mockRestore());
  const { result } = renderHook(() => useArticleDrafts(alice));
  let created: ArticleDraft | undefined;
  await act(async () => { created = await result.current.create(); });
  await act(async () => initial.resolve([draft("stale-load")]));
  expect(result.current.draft!.id).toBe(created!.id);
  expect(result.current.drafts.map(row => row.id)).toEqual([created!.id]);
});
it("new edits made during a slow selection remain open", async () => {
  await Storage.saveArticleDraft(alice, draft("one"));
  const { result } = renderHook(() => useArticleDrafts(alice));
  await waitFor(() => expect(result.current.loading).toBe(false));
  const pending = deferred<ArticleDraft | undefined>();
  const get = spyOn(Storage, "getArticleDraft").mockReturnValue(pending.promise); restores.push(() => get.mockRestore());
  const selecting = result.current.select("two");
  await waitFor(() => expect(get).toHaveBeenCalled());
  act(() => result.current.update({ markdown: "Typed while selection was loading" }));
  await act(async () => { pending.resolve(draft("two")); await selecting; });
  expect(result.current.draft!.id).toBe("one");
  expect(result.current.draft!.markdown).toBe("Typed while selection was loading");
});
it("an incorrectly reused hook refuses writes under another viewer DID", async () => {
  await Storage.saveArticleDraft(alice, draft("private-alice"));
  const { result, rerender } = renderHook(({ did }) => useArticleDrafts(did), { initialProps: { did: alice } });
  await waitFor(() => expect(result.current.loading).toBe(false));
  rerender({ did: bob });
  await expect(result.current.create()).rejects.toThrow("account changed");
  expect(() => result.current.update({ markdown: "Cross-account write" })).toThrow("account changed");
  expect(await Storage.listArticleDrafts(bob)).toEqual([]);
});
for (const action of ["create", "remove"] as const) it(`a concurrent ${action} cannot proceed after an in-flight save fails`, async () => {
  await Storage.saveArticleDraft(alice, draft("one"));
  const { result } = renderHook(() => useArticleDrafts(alice));
  await waitFor(() => expect(result.current.loading).toBe(false));
  const gate = deferred<ArticleDraft>();
  const save = spyOn(Storage, "saveArticleDraft").mockReturnValue(gate.promise); restores.push(() => save.mockRestore());
  const remove = spyOn(Storage, "deleteArticleDraft"); restores.push(() => remove.mockRestore());
  act(() => result.current.update({ markdown: "Private unsaved edits" }));
  const saving = result.current.persist().catch(() => undefined);
  let transitionFailure: unknown;
  const transition = (action === "create" ? result.current.create() : result.current.remove("one")).catch(error => { transitionFailure = error; });
  await act(async () => { gate.reject(new Error("Storage full")); await Promise.all([saving, transition]); });
  expect(transitionFailure).toBeDefined();
  expect(result.current.draft!.markdown).toBe("Private unsaved edits");
  expect(save).toHaveBeenCalledTimes(1);
  expect(remove).not.toHaveBeenCalled();
});
it("explicitly retrying a failed save recovers without losing the open edits", async () => {
  await Storage.saveArticleDraft(alice, draft("one"));
  const { result } = renderHook(() => useArticleDrafts(alice));
  await waitFor(() => expect(result.current.loading).toBe(false));
  const original = Storage.saveArticleDraft;
  const save = spyOn(Storage, "saveArticleDraft").mockRejectedValueOnce(new Error("Temporary quota failure")); restores.push(() => save.mockRestore());
  act(() => result.current.update({ markdown: "Retry these edits" }));
  await act(async () => { await expect(result.current.persist()).rejects.toThrow("Temporary quota failure"); });
  save.mockImplementation(original);
  await act(async () => result.current.persist());
  expect(result.current.error === undefined).toBe(true);
  expect(result.current.status).toBe("Saved in This Browser");
  expect((await Storage.getArticleDraft(alice, "one"))!.markdown).toBe("Retry these edits");
});
