package wireworkercore

var languageNames = map[string]string{
	"arabic":     "ar",
	"bengali":    "bn",
	"chinese":    "zh",
	"czech":      "cs",
	"danish":     "da",
	"dutch":      "nl",
	"english":    "en",
	"finnish":    "fi",
	"french":     "fr",
	"german":     "de",
	"greek":      "el",
	"hebrew":     "he",
	"hindi":      "hi",
	"hungarian":  "hu",
	"indonesian": "id",
	"italian":    "it",
	"japanese":   "ja",
	"korean":     "ko",
	"malay":      "ms",
	"norwegian":  "no",
	"persian":    "fa",
	"polish":     "pl",
	"portuguese": "pt",
	"romanian":   "ro",
	"russian":    "ru",
	"spanish":    "es",
	"swedish":    "sv",
	"thai":       "th",
	"turkish":    "tr",
	"ukrainian":  "uk",
	"vietnamese": "vi",
}
