"use client";
import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { searchSportsEntities, getSportsCatalog, type SportsSelection, type SportsEntity } from "@/lib/sportsFeedClient";
import { SportsPublicInterestDialog } from "@/components/SportsPublicInterestDialog";
import { acknowledgeSportsPublicInterests, readSportsPublicInterestConsent } from "@/lib/sportsPublicInterestConsent";
import { displaySportsEntityName } from "@/lib/sportsDisplayNames";
import { useSportsDisplayLocale } from "@/hooks/useSportsDisplayLocale";
const entityKindLabels: Record<string,string> = {sport:"Sport",competition:"Competition",classification:"Class or Medley Index",team:"Team","national-side":"National Side","ncaa-team":"NCAA Team",school:"School",organization:"Program",athlete:"Athlete",driver:"Driver"};
export function SportsCustomize({open,onOpenChange,selections,save,saving,signedIn,viewerDID}:{open:boolean;onOpenChange:(open:boolean)=>void;selections:SportsSelection[];save:(args:{selection:SportsSelection;remove:boolean})=>Promise<unknown>;saving:boolean;signedIn:boolean;viewerDID?:string}) {
 const locale=useSportsDisplayLocale();
 const entityName=(entity:SportsEntity|undefined,fallback:string)=>entity?displaySportsEntityName(entity,locale):fallback;
 const [search,setSearch]=useState(""); const [query,setQuery]=useState(""); const [consentAccount,setConsentAccount]=useState<string|null>(()=>readSportsPublicInterestConsent(viewerDID)?viewerDID!:null);
 const consent=!!viewerDID&&signedIn&&consentAccount===viewerDID; const [error,setError]=useState<string|null>(null);
 useEffect(()=>{
  if (!open) return;
  // A controlled parent opening the dialog bypasses Dialog's onOpenChange callback.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setSearch("");setQuery("");setConsentAccount(readSportsPublicInterestConsent(viewerDID)?viewerDID!:null);setError(null);
 },[open,viewerDID]);
 useEffect(()=>{const timer=setTimeout(()=>setQuery(search.trim()),300);return()=>clearTimeout(timer);},[search]);
 const catalog=useQuery({queryKey:["sportsCatalog"],queryFn:({signal})=>getSportsCatalog(signal),enabled:open,staleTime:5*60000});
 const results=useQuery({queryKey:["sportsEntitySearch",query],queryFn:({signal})=>searchSportsEntities(query,signal),enabled:open&&query.length>=2,staleTime:60000});
 const entities=(catalog.data?.entities??[]).filter(entity=>entity.active);
 const change=async(reference:string,action:SportsSelection["action"],remove=false)=>{if(!signedIn||!consent||saving)return;const previous=selections.find(s=>s.reference===reference);const now=new Date().toISOString();setError(null);try{await save({selection:{reference,action,createdAt:previous?.createdAt??now,updatedAt:now},remove});}catch(e){setError(e instanceof Error?e.message:"Could not save interest.");}};
 const row=(entity:SportsEntity)=><div key={entity.id} className="flex flex-wrap items-center gap-2 rounded-md border p-2"><div className="min-w-0 flex-1 basis-36"><p className="font-medium">{displaySportsEntityName(entity,locale)}</p><p className="text-xs text-muted-foreground">{entityKindLabels[entity.kind]??entity.kind}{entity.sportID ? ` · ${entityName(entities.find(e=>e.id===entity.sportID),entity.sportID)}`:""}</p></div><div className="flex shrink-0 gap-2">{(["follow","mute"] as const).map(action=><Button key={action} size="sm" variant={selections.some(s=>s.reference===entity.id&&s.action===action)?"secondary":"outline"} aria-pressed={selections.some(s=>s.reference===entity.id&&s.action===action)} disabled={saving||!signedIn||!consent} onClick={()=>void change(entity.id,action,selections.some(s=>s.reference===entity.id&&s.action===action))}>{action==="follow"?"Follow":"Mute"}</Button>)}</div></div>;
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="flex max-h-[calc(100dvh-2rem)] min-h-0 w-[calc(100vw-2rem)] max-w-2xl flex-col gap-0 overflow-hidden p-0 sm:max-w-2xl"><DialogHeader className="shrink-0 p-4 pr-12"><DialogTitle>Customize Sports</DialogTitle><DialogDescription>Choose sports, teams, and people to follow or mute.</DialogDescription></DialogHeader><div data-sports-customize-body className="min-h-0 min-w-0 flex-1 space-y-4 overflow-y-auto overscroll-contain px-4 pb-4 [overflow-wrap:anywhere]">{!signedIn?<p>Sign In to save interests.</p>:null}<label className="text-sm">Find Sports, Competitions, Teams, or People<input type="search" className="mt-2 w-full rounded-md border bg-background p-2" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="space-y-2">{(query.length>=2?(results.data?.entities??[]):entities.filter(e=>e.kind==="sport").sort((a,b)=>displaySportsEntityName(a,locale).localeCompare(displaySportsEntityName(b,locale)))).map(row)}</div>{query.length >= 2 && results.isPending ? <p role="status">Searching Sports…</p> : null}{query.length >= 2 && results.isSuccess && !results.data.entities.length ? <p role="status">No supported entities match your search.</p> : null}<h3 className="font-semibold">Your Interests</h3><div className="space-y-2">{selections.map(s=><div key={s.reference} className="flex items-center gap-2 text-sm"><span className="min-w-0 flex-1">{entityName(entities.find(e=>e.id===s.reference),"Saved Interest")} · {s.action==="follow"?"Following":"Muted"}</span><Button size="sm" variant="outline" disabled={saving||!consent} onClick={()=>void change(s.reference,s.action,true)}>Remove</Button></div>)}</div><p className="text-xs text-muted-foreground">Following a team or person overrides a broader sport or competition mute. Explicitly muted teams or people remain excluded. Hide Scores hides event results, not article headlines or images.</p>{error||results.error||catalog.error?<p role="alert">{error??"Reference catalog unavailable. Try again."}</p>:null}</div><div data-sports-customize-footer className="shrink-0 border-t px-4 py-3"><DialogClose render={<Button variant="outline" className="w-full sm:w-auto"/>}>Close</DialogClose></div><SportsPublicInterestDialog open={open&&signedIn&&!consent} onAccept={()=>{if(!viewerDID)return;acknowledgeSportsPublicInterests(viewerDID);setConsentAccount(viewerDID);}} onCancel={()=>onOpenChange(false)}/></DialogContent></Dialog>;
}
