public enum SportsReviewedCollegeRosters {
  // Reviewed on 2026-10-04 for the 2026-27 season. Facts only; no logos or source prose.
  // This is a supported subset, not a claim of complete NCAA institution/sport coverage.
  static let conferences: [SportsReviewedCollegeConference] = [
    .init(key: "gliac", name: "Great Lakes Intercollegiate Athletic Conference", division: "Division II", sportKey: "ncaa-football", label: "Football", schools: "Davenport|Ferris State|Grand Valley State|Michigan Tech|Roosevelt|Saginaw Valley State|Northern Michigan|Wayne State University".split(separator: "|").map(String.init), source: "https://gliac.org/standings.aspx?path=football"),
    .init(key: "miaa", name: "Mid-America Intercollegiate Athletics Association", division: "Division II", sportKey: "ncaa-football", label: "Football", schools: "Emporia State|Central Missouri|Northwest Missouri State|Washburn|Fort Hays State|Central Oklahoma|Missouri Western State|Pittsburg State|Missouri Southern State|Nebraska Kearney".split(separator: "|").map(String.init), source: "https://themiaa.com/standings.aspx?path=football"),
    .init(key: "siac", name: "Southern Intercollegiate Athletic Conference", division: "Division II", sportKey: "ncaa-football", label: "Football", schools: "Kentucky State|Edward Waters|Tuskegee|Central State|Miles|Benedict|Albany State|Allen|Morehouse|Clark Atlanta|Fort Valley State|Savannah State|Lane".split(separator: "|").map(String.init), source: "https://thesiac.com/standings.aspx?path=fball"),
    .init(key: "nsic", name: "Northern Sun Intercollegiate Conference", division: "Division II", sportKey: "ncaa-football", label: "Football", schools: "Northern State|MSU Moorhead|Bemidji State|Jamestown|Minnesota Duluth|University of Mary|Minot State|Minnesota State|Wayne State College|Winona State|Concordia-St. Paul|Sioux Falls|Augustana|Southwest Minnesota State".split(separator: "|").map(String.init), source: "https://northernsun.org/standings.aspx?path=football"),
    .init(key: "gliac", name: "Great Lakes Intercollegiate Athletic Conference", division: "Division II", sportKey: "ncaa-womens-basketball", label: "Women's Basketball", schools: "Davenport|Ferris State|Grand Valley State|Lake Superior State|Michigan Tech|Northern Michigan|Parkside|Purdue Northwest|Roosevelt|Saginaw Valley State|Wayne State University".split(separator: "|").map(String.init), source: "https://gliac.org/standings.aspx?path=wbball"),
    .init(key: "miaa", name: "Mid-America Intercollegiate Athletics Association", division: "Division II", sportKey: "ncaa-womens-basketball", label: "Women's Basketball", schools: "Arkansas-Fort Smith|Central Missouri|Central Oklahoma|Emporia State|Fort Hays State|Missouri Southern State|Missouri Western State|Nebraska Kearney|Newman|Northeastern State|Northwest Missouri State|Pittsburg State|Rogers State|Washburn".split(separator: "|").map(String.init), source: "https://themiaa.com/standings.aspx?path=wbball"),
    .init(key: "centennial", name: "Centennial Conference", division: "Division III", sportKey: "ncaa-football", label: "Football", schools: "Johns Hopkins|Carnegie Mellon|Franklin & Marshall|Muhlenberg|Ursinus|Dickinson|Gettysburg|McDaniel".split(separator: "|").map(String.init), source: "https://centennial.org/news/2026/8/16/johns-hopkins-headlines-cc-football-preseason-poll.aspx"),
    .init(key: "oac", name: "Ohio Athletic Conference", division: "Division III", sportKey: "ncaa-football", label: "Football", schools: "Baldwin Wallace|Heidelberg|Mount Union|Marietta|Ohio Northern|Capital|Otterbein|Wilmington|Muskingum".split(separator: "|").map(String.init), source: "https://oac.org/stats.aspx?path=football&year=2026"),
    .init(key: "uaa", name: "University Athletic Association", division: "Division III", sportKey: "ncaa-mens-basketball", label: "Men's Basketball", schools: "Brandeis|Carnegie Mellon|Case Western Reserve|Chicago|Emory|New York University|Rochester|Washington University in St. Louis".split(separator: "|").map(String.init), source: "https://uaasports.info/standings.aspx?path=mbball"),
    .init(key: "uaa", name: "University Athletic Association", division: "Division III", sportKey: "ncaa-womens-basketball", label: "Women's Basketball", schools: "Brandeis|Carnegie Mellon|Case Western Reserve|Chicago|Emory|New York University|Rochester|Washington University in St. Louis".split(separator: "|").map(String.init), source: "https://uaasports.info/standings.aspx?path=wbball"),
  ]
}
