/// Reviewed against WGI's August 2026 Policy Manual, 2026 finalist reviews and supplemental group-season entries.
/// This is a season-labelled reference snapshot, not a live roster or event-data adapter.
/// Group keys omit competitive class; distinct disciplines/ensemble formats retain identities.
enum SportsReviewedWGI {
  static let classes: [(code: String, discipline: String, category: String, format: String, level: String)] = [
    ("sra", "color-guard", "Scholastic", "", "Regional A"),
    ("sa", "color-guard", "Scholastic", "", "A"),
    ("so", "color-guard", "Scholastic", "", "Open"),
    ("sw", "color-guard", "Scholastic", "", "World"),
    ("ira", "color-guard", "Independent", "", "Regional A"),
    ("ia", "color-guard", "Independent", "", "A"),
    ("io", "color-guard", "Independent", "", "Open"),
    ("iw", "color-guard", "Independent", "", "World"),
    ("psa", "percussion", "Scholastic", "Marching", "A"),
    ("pso", "percussion", "Scholastic", "Marching", "Open"),
    ("psw", "percussion", "Scholastic", "Marching", "World"),
    ("pia", "percussion", "Independent", "Marching", "A"),
    ("pio", "percussion", "Independent", "Marching", "Open"),
    ("piw", "percussion", "Independent", "Marching", "World"),
    ("psca", "percussion", "Scholastic", "Concert", "A"),
    ("psco", "percussion", "Scholastic", "Concert", "Open"),
    ("pscw", "percussion", "Scholastic", "Concert", "World"),
    ("wsa", "winds", "Scholastic", "", "A"),
    ("wso", "winds", "Scholastic", "", "Open"),
    ("wsw", "winds", "Scholastic", "", "World"),
    ("wia", "winds", "Independent", "", "A"),
    ("wio", "winds", "Independent", "", "Open"),
    ("wiw", "winds", "Independent", "", "World"),
  ]
  static let groups: [(code: String, name: String)] = [
    ("sa", "Southington HS"),
    ("sa", "John C. Birdlebough HS"),
    ("sa", "Campbell County HS"),
    ("sa", "Edwardsville HS"),
    ("sa", "Rock Hill HS"),
    ("sa", "Carroll HS (IN)"),
    ("sa", "Rancho Cucamonga HS"),
    ("sa", "Diamond Bar HS"),
    ("sa", "Friendswood HS"),
    ("sa", "Elizabeth HS"),
    ("sa", "Grand Oaks HS"),
    ("sa", "Cooper City HS"),
    ("sa", "Madison Central HS (KY)"),
    ("sa", "Unionville HS"),
    ("sa", "Jersey Village HS"),
    ("sa", "Foothill HS (NV)"),
    ("sa", "Hamilton HS (OH)"),
    ("sa", "Hoover HS (AL) Varsity"),
    ("sa", "Salem HS"),
    ("sa", "Liverpool HS"),
    ("so", "Oviedo HS"),
    ("so", "Timber Creek HS (FL)"),
    ("so", "Brownsburg HS"),
    ("so", "Franklin Central HS"),
    ("so", "Mason HS"),
    ("so", "Dobyns-Bennett HS"),
    ("so", "Wylie HS"),
    ("so", "Amador Valley HS"),
    ("so", "Holly Springs HS"),
    ("so", "Hamilton Southeastern HS"),
    ("so", "Pearland HS"),
    ("so", "James Bowie HS (Austin)"),
    ("so", "Westlake HS (TX)"),
    ("so", "River Bluff HS"),
    ("so", "Ronald Reagan HS"),
    ("sw", "Arcadia HS"),
    ("sw", "Flanagan HS"),
    ("sw", "Avon HS"),
    ("sw", "The Woodlands HS"),
    ("sw", "Tarpon Springs HS"),
    ("sw", "Center Grove HS"),
    ("sw", "Carmel HS"),
    ("sw", "Miamisburg HS"),
    ("sw", "El Dorado HS"),
    ("sw", "Northview HS"),
    ("sw", "Norwin HS"),
    ("sw", "Stoneman Douglas HS"),
    ("sw", "Little Elm HS"),
    ("sw", "Warren Central HS (IN)"),
    ("sw", "Chino Hills HS"),
    ("ia", "Caledonia Independent"),
    ("ia", "Maharlika"),
    ("ia", "Impulse Winterguard"),
    ("ia", "RGV Winter Guard"),
    ("ia", "Orlando Visual"),
    ("ia", "FIU Gold"),
    ("ia", "Anesidora A"),
    ("ia", "Relentless"),
    ("ia", "Sonnor"),
    ("ia", "Rhapsody"),
    ("ia", "Crescent City Color Guard"),
    ("ia", "San Diego State University Aztec Winter Guard"),
    ("ia", "Beau Monde Independent"),
    ("ia", "Old Line Independent Color Guard"),
    ("ia", "Opulence"),
    ("io", "First Flight"),
    ("io", "Homage Independent"),
    ("io", "ORIGINS Open"),
    ("io", "Revival"),
    ("io", "Undaunted"),
    ("io", "Noir Independent"),
    ("io", "Opus Winter Guard"),
    ("io", "Tampa Independent Open"),
    ("io", "Collage Winter Guard"),
    ("io", "Industry Independent"),
    ("io", "NOVA Independent Winterguard"),
    ("io", "George Mason University Winterguard"),
    ("io", "Vestige"),
    ("io", "Sensation Performance Ensemble"),
    ("iw", "Fusion Winter Guard"),
    ("iw", "Paramount"),
    ("iw", "Etude"),
    ("iw", "Fantasia"),
    ("iw", "Blessed Sacrament"),
    ("iw", "Juxtaposition"),
    ("iw", "Origins"),
    ("iw", "Onyx"),
    ("iw", "Vox Artium"),
    ("iw", "Mayflower"),
    ("iw", "Tampa Independent"),
    ("iw", "Lexis"),
    ("iw", "FIU Pegasus World"),
    ("iw", "Phoenix Independent"),
    ("iw", "Anesidora"),
    ("psca", "Warren East HS"),
    ("psca", "New Bedford HS"),
    ("psca", "Pendleton HS"),
    ("psca", "Hatboro-Horsham HS"),
    ("psca", "New Hope HS"),
    ("psca", "Canton McKinley HS"),
    ("psca", "Lowell HS"),
    ("psca", "East Central HS"),
    ("psca", "Price Charter School"),
    ("psca", "Newnan HS"),
    ("psca", "Westside HS"),
    ("psca", "Atoka HS"),
    ("psco", "Klein Collins HS"),
    ("psco", "Ben Davis HS"),
    ("psco", "Kiski Area HS"),
    ("psco", "Munster HS"),
    ("psco", "Cleveland HS"),
    ("psco", "Broadneck HS"),
    ("psco", "Milford HS (OH)"),
    ("psco", "Enka HS"),
    ("psco", "Boiling Springs HS"),
    ("pscw", "Vista Murrieta HS"),
    ("pscw", "Ayala HS"),
    ("pscw", "Grassfield HS"),
    ("pscw", "Fishers HS"),
    ("pscw", "Corona Del Sol HS"),
    ("pscw", "Catawba Ridge HS"),
    ("pscw", "Timber Creek HS (FL)"),
    ("pscw", "Tunstall HS"),
    ("psa", "Alpharetta HS"),
    ("psa", "Kings HS"),
    ("psa", "Weatherford HS"),
    ("psa", "Jordan-Elbridge HS"),
    ("psa", "Owen J. Roberts HS"),
    ("psa", "Hamilton Southeastern HS"),
    ("psa", "E.D. White Catholic HS"),
    ("psa", "Hardin Valley Academy"),
    ("psa", "Temple City HS"),
    ("psa", "Springboro HS"),
    ("psa", "Everett HS"),
    ("psa", "East Coweta HS"),
    ("psa", "Pearl HS"),
    ("psa", "Glencoe HS"),
    ("psa", "Central HS (TX)"),
    ("pso", "Sonia Sotomayor HS"),
    ("pso", "Victor J. Andrews HS"),
    ("pso", "Norwalk HS"),
    ("pso", "Pace HS"),
    ("pso", "Zionsville Community HS"),
    ("pso", "Jordan HS"),
    ("pso", "Beavercreek HS"),
    ("pso", "Greenfield-Central HS"),
    ("pso", "Franklin Community HS"),
    ("pso", "Central Lafourche HS"),
    ("pso", "Auburn HS (AL)"),
    ("pso", "Goshen HS"),
    ("pso", "Brandon Valley HS"),
    ("pso", "Arbor View HS"),
    ("pso", "Sparkman HS"),
    ("psw", "Ayala HS"),
    ("psw", "Vista Murrieta HS"),
    ("psw", "Chino Hills HS"),
    ("psw", "Arcadia HS"),
    ("psw", "Burleson Centennial HS"),
    ("psw", "Bridgeland HS"),
    ("psw", "Clear Brook HS"),
    ("psw", "Saratoga HS"),
    ("psw", "Avon HS"),
    ("psw", "Center Grove HS"),
    ("psw", "Cy-Fair HS"),
    ("psw", "James Logan HS"),
    ("psw", "Broken Arrow HS"),
    ("psw", "Etiwanda HS"),
    ("psw", "Buchanan HS"),
    ("pia", "Ravenwood Indoor Percussion"),
    ("pia", "Nomad Indoor"),
    ("pia", "South County Combined"),
    ("pia", "Lake Effect Percussion"),
    ("pia", "Francis Howell Percussion"),
    ("pia", "Pi Percussion Inc"),
    ("pia", "Horizon Percussion"),
    ("pia", "Vortex Percussion"),
    ("pia", "202 Indoor Percussion"),
    ("pia", "Revelation A"),
    ("pia", "North Star Independent"),
    ("pia", "Boise Gems Independent"),
    ("pia", "Legacy Percussion"),
    ("pia", "Spark Percussion"),
    ("pia", "East Mississippi Em-pact"),
    ("pio", "United Percussion 2"),
    ("pio", "Veritas"),
    ("pio", "UTSA"),
    ("pio", "Cap City 2"),
    ("pio", "Bakersfield College"),
    ("pio", "Q2"),
    ("pio", "Spectre Percussion"),
    ("pio", "Paradigm Percussion"),
    ("pio", "Sparta Indoor Percussion"),
    ("pio", "Motor City Percussion"),
    ("pio", "Infinity 3"),
    ("pio", "Matrix Open"),
    ("pio", "Freedom Percussion"),
    ("pio", "Sun City Independent"),
    ("pio", "Imperial Dynasty"),
    ("pio", "Buckhorn Percussion"),
    ("piw", "United Percussion"),
    ("piw", "Rhythm X"),
    ("piw", "RCC"),
    ("piw", "Pulse Percussion"),
    ("piw", "Music City Mystique"),
    ("piw", "Broken City"),
    ("piw", "Infinity"),
    ("piw", "George Mason University"),
    ("piw", "Rhythmic Force Percussion"),
    ("piw", "POW Percussion"),
    ("piw", "Atlanta Quest"),
    ("piw", "Dark Sky Percussion"),
    ("piw", "Matrix"),
    ("piw", "Redline"),
    ("piw", "Cap City"),
    ("piw", "Infinity 2"),
    ("wsa", "Damien HS"),
    ("wsa", "North Lincoln HS"),
    ("wsa", "Newnan HS"),
    ("wsa", "Mt. Juliet HS"),
    ("wsa", "Gulfport HS"),
    ("wsa", "Papillion-La Vista South HS"),
    ("wsa", "Ohio County HS"),
    ("wsa", "New Bedford HS"),
    ("wsa", "Lake Orion HS"),
    ("wsa", "John Hardin HS"),
    ("wsa", "Crescent HS"),
    ("wsa", "Simon Kenton HS"),
    ("wia", "Hydra Winds presented by Atlanta CV"),
    ("wia", "Vortex Indoor Winds"),
    ("wia", "Del Sol Winds"),
    ("wia", "Cyclone Winds"),
    ("wia", "ICT Winds"),
    ("wia", "Carlisle HS"),
    ("wso", "Daviess County HS"),
    ("wso", "Valley Christian HS"),
    ("wso", "Washington HS (IN)"),
    ("wso", "Miamisburg HS"),
    ("wso", "Warren Central HS (IN)"),
    ("wso", "John I. Leonard HS"),
    ("wso", "Oviedo Winds"),
    ("wio", "Obsidian Winds"),
    ("wio", "River City Rhythm"),
    ("wio", "STRYKE Wynds 2"),
    ("wio", "Valhalla Winds"),
    ("wio", "Elevate Winds"),
    ("wio", "Ethereal Winds"),
    ("wio", "Forest Hills"),
    ("wio", "MBI Winds"),
    ("wio", "LSM West"),
    ("wio", "Convergence Indoor Winds"),
    ("wsw", "Avon HS"),
    ("wsw", "Catawba Ridge HS"),
    ("wsw", "Greenfield Central HS"),
    ("wsw", "South Jones HS"),
    ("wsw", "Westfield HS"),
    ("wsw", "Lake Hamilton HS"),
    ("wiw", "STRYKE Wynds"),
    ("wiw", "Vaquero Winds"),
    ("wiw", "Horizon Winds"),
    ("wiw", "LSM Winds"),
    ("wiw", "Legacy"),
  ]


  // Explicit 2026 prelim class assignments from WGI's official University of Dayton/Truist rosters.
  static let supplementalPrelimGroups: [(code: String, name: String)] = [
    ("psw", "Milton HS"),
    ("psw", "Fishers HS"),
    ("psw", "Walled Lake Consolidated Schools"),
    ("psw", "Mt. Juliet HS"),
    ("psw", "Franklin Central HS"),
    ("psw", "Greenwood HS"),
    ("psw", "Foothill HS (NV)"),
    ("psw", "Fair Lawn HS"),
    ("psw", "Dorman HS"),
    ("psw", "Brownsburg HS"),
    ("psw", "Carroll HS (IN)"),
    ("psw", "Homestead HS (CA)"),
    ("piw", "IMPACT Percussion"),
    ("piw", "Rise Percussion"),
    ("piw", "Flux Indoor Percussion"),
    ("piw", "Red Wave Indoor from Fresno State"),
    ("piw", "Civitas Independent"),
    ("piw", "Monarch Independent"),
    ("piw", "MBI Indoor Percussion"),
    ("piw", "Kaizen Percussion"),
    ("piw", "STRYKE Percussion"),
    ("piw", "Instinct"),
    ("piw", "Blue Knights"),
    ("piw", "Resistance Indoor Percussion"),
    ("piw", "Vigilantes Indoor Percussion"),
    ("piw", "ConneXus"),
    ("piw", "Audio Theater"),
    ("piw", "Meraki"),
    ("pia", "NorthCoast Academy"),
    ("pia", "Carolina Storm Indoor Percussion"),
    ("pia", "Breakwater Performing Arts"),
    ("pia", "Albemarle County Indoor Percussion"),
    ("pia", "Saints Indoor Percussion"),
    ("pia", "Palmetto Indoor Theatre"),
    ("pia", "IGNITE Winter Percussion"),
    ("pio", "OCI Percussion"),
    ("pio", "Tri-City Percussion"),
    ("pio", "Modulation Z"),
    ("pio", "Charles Towne Percussion"),
    ("pio", "River City Rhythm"),
    ("pio", "Rift Percussion"),
    ("pio", "Old Line Independent Percussion"),
    ("pio", "Kannapolis Independent"),
    ("pio", "Dakota Combined Schools"),
    ("pio", "Huron Valley Percussion"),
    ("pio", "Vision Percussion"),
    ("pio", "Convergence Indoor Percussion"),
    ("pio", "Rock Ridge HS Combined"),
    ("pio", "Grandville Independent Percussion"),
    ("pio", "Siege Percussion"),
    ("pio", "Synergy"),
    ("pio", "Gold Spike Percussion"),
    ("pio", "Breakthrough Indoor Percussion"),
    ("pio", "Desert Vox"),
    ("pio", "Revelation Open"),
    ("pio", "Lotus"),
  ]

  // Primary identity evidence: United's 2027 audition page distinguishes World and Open programs.
  static let supplementalAliases: [String: [String]] = [
    "United Percussion": ["United Percussion World", "UPW"],
    "United Percussion 2": ["UP2"],
  ]

  static func disciplineName(_ key: String) -> String {
    switch key { case "color-guard": "Color Guard"; case "percussion": "Percussion"; default: "Winds" }
  }

  static func groupKey(discipline: String, format: String, name: String) -> String {
    "team:wgi:" + discipline + ":" + (format.isEmpty ? "ensemble" : format.lowercased()) + ":"
      + SportsResolver.normalize(name).replacingOccurrences(of: " ", with: "-")
  }

  static var entities: [SportsEntity] {
    let sport = SportsReviewedCatalog.id("sport:indoor-marching-arts")
    let wgi = SportsReviewedCatalog.id("competition:wgi")
    var result: [SportsEntity] = [.init(id: wgi, name: "Winter Guard International", kind: "competition",
      sportID: sport, aliases: ["WGI", "WGI Sport of the Arts"], groupPath: ["Marching Arts", "WGI"])]
    for key in ["color-guard", "percussion", "winds"] {
      let name = "WGI " + disciplineName(key)
      result.append(.init(id: SportsReviewedCatalog.id("competition:wgi-" + key), name: name,
        kind: "competition", sportID: sport, competitionIDs: [wgi],
        aliases: key == "color-guard" ? ["WGI Guard", "WGI Colour Guard"] : [],
        groupPath: ["Marching Arts", "WGI", name]))
    }
    for entry in classes {
      let discipline = SportsReviewedCatalog.id("competition:wgi-" + entry.discipline)
      let classID = SportsReviewedCatalog.id("competition:wgi-class:" + entry.code)
      let base = "WGI " + disciplineName(entry.discipline)
      let label = entry.category + " " + (entry.format.isEmpty ? "" : entry.format + " ") + entry.level
      let path = ["Marching Arts", "WGI", base] + (entry.format.isEmpty ? [] : [entry.format])
        + [entry.category, entry.level + " Class"]
      let aliases = [entry.code.uppercased()] + (entry.format == "Marching"
        ? [base + " " + entry.category + " " + entry.level] : [])
      result.append(.init(id: classID, name: base + " " + label, kind: "competition", sportID: sport,
        competitionIDs: [discipline, wgi], aliases: aliases, division: label, groupPath: path))
      for group in groups + supplementalPrelimGroups where group.code == entry.code {
        let suffix = entry.discipline == "color-guard" ? "Color Guard"
          : entry.discipline == "percussion" ? entry.format + " Percussion" : "Winds"
        let scholastic = entry.category == "Scholastic"
        let name = scholastic ? group.name + " " + suffix : group.name
        result.append(.init(id: SportsReviewedCatalog.id(groupKey(discipline: entry.discipline,
          format: entry.format, name: group.name)), name: name, kind: "team", sportID: sport,
          competitionIDs: [classID, discipline, wgi], aliases: scholastic ? [group.name] : supplementalAliases[group.name] ?? [],
          division: "2026 " + label, groupPath: path))
      }
    }
    return result
  }
}
