/// Reviewed display codes keyed by canonical identity; never derived from names or resolver aliases.
public enum SportsTeamAbbreviations {
  // Reviewed 2026-10-04. NFL official 2026 rulebook Team Abbreviation Codes:
  // https://operations.nfl.com/rules-officiating/2026-nfl-rulebook
  // MLB official team reference: https://statsapi.mlb.com/api/v1/teams?sportId=1
  // NHL reviewed PHI/NJD fixture: https://www.nhl.com/de/gamecenter/phi-vs-njd/2026/10/01/2026020009
  private static let codes: [String: String] = Dictionary(uniqueKeysWithValues: [
    (SportsReviewedCatalog.id("team:nfl:Arizona Cardinals"), "ARZ"),
    (SportsReviewedCatalog.id("team:nfl:Atlanta Falcons"), "ATL"),
    (SportsReviewedCatalog.id("team:nfl:Baltimore Ravens"), "BLT"),
    (SportsReviewedCatalog.id("team:nfl:Buffalo Bills"), "BUF"),
    (SportsReviewedCatalog.id("team:nfl:Carolina Panthers"), "CAR"),
    (SportsReviewedCatalog.id("team:nfl:Chicago Bears"), "CHI"),
    (SportsReviewedCatalog.id("team:nfl:Cincinnati Bengals"), "CIN"),
    (SportsReviewedCatalog.id("team:nfl:Cleveland Browns"), "CLV"),
    (SportsReviewedCatalog.id("team:nfl:Dallas Cowboys"), "DAL"),
    (SportsReviewedCatalog.id("team:nfl:Denver Broncos"), "DEN"),
    (SportsReviewedCatalog.id("team:nfl:Detroit Lions"), "DET"),
    (SportsReviewedCatalog.id("team:nfl:Green Bay Packers"), "GB"),
    (SportsReviewedCatalog.id("team:nfl:Houston Texans"), "HST"),
    (SportsReviewedCatalog.id("team:nfl:Indianapolis Colts"), "IND"),
    (SportsReviewedCatalog.id("team:nfl:Jacksonville Jaguars"), "JAX"),
    (SportsReviewedCatalog.id("team:nfl:Kansas City Chiefs"), "KC"),
    (SportsReviewedCatalog.id("team:nfl:Las Vegas Raiders"), "LV"),
    (SportsReviewedCatalog.id("team:nfl:Los Angeles Chargers"), "LAC"),
    (SportsReviewedCatalog.id("team:nfl:Los Angeles Rams"), "LAR"),
    (SportsReviewedCatalog.id("team:nfl:Miami Dolphins"), "MIA"),
    (SportsReviewedCatalog.id("team:nfl:Minnesota Vikings"), "MIN"),
    (SportsReviewedCatalog.id("team:nfl:New England Patriots"), "NE"),
    (SportsReviewedCatalog.id("team:nfl:New Orleans Saints"), "NO"),
    (SportsReviewedCatalog.id("team:nfl:New York Giants"), "NYG"),
    (SportsReviewedCatalog.id("team:nfl:New York Jets"), "NYJ"),
    (SportsReviewedCatalog.id("team:nfl:Philadelphia Eagles"), "PHI"),
    (SportsReviewedCatalog.id("team:nfl:Pittsburgh Steelers"), "PIT"),
    (SportsReviewedCatalog.id("team:nfl:San Francisco 49ers"), "SF"),
    (SportsReviewedCatalog.id("team:nfl:Seattle Seahawks"), "SEA"),
    (SportsReviewedCatalog.id("team:nfl:Tampa Bay Buccaneers"), "TB"),
    (SportsReviewedCatalog.id("team:nfl:Tennessee Titans"), "TEN"),
    (SportsReviewedCatalog.id("team:nfl:Washington Commanders"), "WAS"),
    (SportsReviewedCatalog.id("team:mlb:Athletics"), "ATH"),
    (SportsReviewedCatalog.id("team:mlb:Pittsburgh Pirates"), "PIT"),
    (SportsReviewedCatalog.id("team:mlb:San Diego Padres"), "SD"),
    (SportsReviewedCatalog.id("team:mlb:Seattle Mariners"), "SEA"),
    (SportsReviewedCatalog.id("team:mlb:San Francisco Giants"), "SF"),
    (SportsReviewedCatalog.id("team:mlb:St. Louis Cardinals"), "STL"),
    (SportsReviewedCatalog.id("team:mlb:Tampa Bay Rays"), "TB"),
    (SportsReviewedCatalog.id("team:mlb:Texas Rangers"), "TEX"),
    (SportsReviewedCatalog.id("team:mlb:Toronto Blue Jays"), "TOR"),
    (SportsReviewedCatalog.id("team:mlb:Minnesota Twins"), "MIN"),
    (SportsReviewedCatalog.id("team:mlb:Philadelphia Phillies"), "PHI"),
    (SportsReviewedCatalog.id("team:mlb:Atlanta Braves"), "ATL"),
    (SportsReviewedCatalog.id("team:mlb:Chicago White Sox"), "CWS"),
    (SportsReviewedCatalog.id("team:mlb:Miami Marlins"), "MIA"),
    (SportsReviewedCatalog.id("team:mlb:New York Yankees"), "NYY"),
    (SportsReviewedCatalog.id("team:mlb:Milwaukee Brewers"), "MIL"),
    (SportsReviewedCatalog.id("team:mlb:Los Angeles Angels"), "LAA"),
    (SportsReviewedCatalog.id("team:mlb:Arizona Diamondbacks"), "AZ"),
    (SportsReviewedCatalog.id("team:mlb:Baltimore Orioles"), "BAL"),
    (SportsReviewedCatalog.id("team:mlb:Boston Red Sox"), "BOS"),
    (SportsReviewedCatalog.id("team:mlb:Chicago Cubs"), "CHC"),
    (SportsReviewedCatalog.id("team:mlb:Cincinnati Reds"), "CIN"),
    (SportsReviewedCatalog.id("team:mlb:Cleveland Guardians"), "CLE"),
    (SportsReviewedCatalog.id("team:mlb:Colorado Rockies"), "COL"),
    (SportsReviewedCatalog.id("team:mlb:Detroit Tigers"), "DET"),
    (SportsReviewedCatalog.id("team:mlb:Houston Astros"), "HOU"),
    (SportsReviewedCatalog.id("team:mlb:Kansas City Royals"), "KC"),
    (SportsReviewedCatalog.id("team:mlb:Los Angeles Dodgers"), "LAD"),
    (SportsReviewedCatalog.id("team:mlb:Washington Nationals"), "WSH"),
    (SportsReviewedCatalog.id("team:mlb:New York Mets"), "NYM"),
    (SportsReviewedCatalog.id("team:nhl:Philadelphia Flyers"), "PHI"),
    (SportsReviewedCatalog.id("team:nhl:New Jersey Devils"), "NJD")
  ])

  public static func abbreviation(entityID: String?) -> String? {
    entityID.flatMap { codes[$0] ?? SportsReviewedAmateurAbbreviations.codes[$0] }
  }
}
