/// Reviewed official 2026 Grand Nationals participants on October 4, 2026.
/// Current band classifications are not published before/during events and are not inferred.
enum SportsReviewedBOA {
  static let bands: [(name: String, state: String)] = [
    ("Allegan HS", "MI"),
    ("American Fork HS", "UT"),
    ("Archbishop Alter HS", "OH"),
    ("Archbishop Carroll HS", "OH"),
    ("Arlington HS", "TN"),
    ("Avon HS", "IN"),
    ("Bartlett HS", "TN"),
    ("Batesville HS", "IN"),
    ("Beechwood HS", "KY"),
    ("Bourbon County HS", "KY"),
    ("Broken Arrow HS", "OK"),
    ("Brownsburg HS", "IN"),
    ("Cabell Midland HS", "WV"),
    ("Carlisle HS", "OH"),
    ("Carmel HS", "IN"),
    ("Castle HS", "IN"),
    ("Catawba Ridge HS", "SC"),
    ("Center Grove HS", "IN"),
    ("Centerville HS", "OH"),
    ("Chesapeake HS", "OH"),
    ("Christian Academy of Louisville", "KY"),
    ("Christian County HS", "KY"),
    ("Clarksville HS", "TN"),
    ("Clinton-Massie HS", "OH"),
    ("Colerain HS", "OH"),
    ("Columbus HS", "IN"),
    ("DeWitt HS", "MI"),
    ("Downingtown West HS", "PA"),
    ("East Clinton HS", "OH"),
    ("Elizabethton HS", "TN"),
    ("Fairborn HS", "OH"),
    ("Finneytown HS", "OH"),
    ("Fishers HS", "IN"),
    ("Floyd Central HS", "IN"),
    ("Forest Hills Schools", "OH"),
    ("Franklin HS", "TN"),
    ("Friendswood HS", "TX"),
    ("George Rogers Clark HS", "KY"),
    ("Green Canyon HS", "UT"),
    ("Green Level HS", "NC"),
    ("Greendale HS", "WI"),
    ("Greenwood Community HS", "IN"),
    ("Hamilton HS", "OH"),
    ("Hardin Valley Academy", "TN"),
    ("Harrison County HS", "KY"),
    ("Harrison HS", "GA"),
    ("Highlands HS", "KY"),
    ("Homestead HS", "IN"),
    ("Huron Valley Marching Band", "MI"),
    ("Independence HS", "VA"),
    ("James Bowie HS", "TX"),
    ("Jenison HS", "MI"),
    ("John Hardin HS", "KY"),
    ("Kalida HS", "OH"),
    ("Kickapoo HS", "MO"),
    ("Lafayette HS", "KY"),
    ("Lake Hamilton HS", "AR"),
    ("Lakota East HS", "OH"),
    ("Lambert HS", "GA"),
    ("Lawrence Township", "IN"),
    ("Legacy HS", "CO"),
    ("Lincoln-Way Community HS", "IL"),
    ("Marian Catholic HS", "IL"),
    ("Marion Local HS", "OH"),
    ("Mauldin HS", "SC"),
    ("McKinney HS", "TX"),
    ("McNeil HS", "TX"),
    ("Miamisburg HS", "OH"),
    ("Milford HS", "OH"),
    ("Mililani HS", "HI"),
    ("Moe & Gene Johnson HS", "TX"),
    ("Monrovia HS", "IN"),
    ("Mustang HS", "OK"),
    ("Newberry HS", "FL"),
    ("Noblesville HS", "IN"),
    ("Norton HS", "OH"),
    ("Norwood HS", "OH"),
    ("O'Fallon Township HS", "IL"),
    ("Pike County Central HS", "KY"),
    ("Reeths-Puffer HS", "MI"),
    ("Rockford HS", "MI"),
    ("Seven Lakes HS", "TX"),
    ("Shawe Memorial HS", "IN"),
    ("South Dearborn HS", "IN"),
    ("South Point HS", "OH"),
    ("Springboro HS", "OH"),
    ("Talawanda HS", "OH"),
    ("Tarpon Springs HS", "FL"),
    ("Union HS", "OK"),
    ("Vista Murrieta HS", "CA"),
    ("Walter E. Stebbins HS", "OH"),
    ("Warren Local HS", "OH"),
    ("Westfield HS", "IN"),
    ("Westlake HS", "UT"),
    ("Westwood HS", "TX"),
    ("William Mason HS", "OH"),
    ("Wilmington HS", "OH"),
    ("Worthington Kilbourne HS", "OH"),
  ]

  static var entities: [SportsEntity] {
    let sport = SportsReviewedCatalog.id("sport:marching-arts")
    let boa = SportsReviewedCatalog.id("competition:boa")
    let grandNationals = SportsReviewedCatalog.id("competition:boa-grand-nationals")
    var result: [SportsEntity] = [
      .init(id: boa, name: "Bands of America", kind: "competition", sportID: sport,
        aliases: ["BOA"], groupPath: ["Marching Arts", "BOA"]),
      .init(id: grandNationals, name: "BOA Grand National Championships", kind: "competition", sportID: sport,
        competitionIDs: [boa], aliases: ["Bands of America Grand National Championships", "BOA Grand Nationals"],
        groupPath: ["Marching Arts", "BOA", "Grand Nationals"])
    ]
    for code in ["A", "AA", "AAA", "AAAA"] {
      result.append(.init(id: SportsReviewedCatalog.id("competition:boa-class:" + code.lowercased()),
        name: "BOA Class " + code, kind: "competition", sportID: sport, competitionIDs: [boa],
        aliases: ["Bands of America Class " + code], division: "Class " + code,
        groupPath: ["Marching Arts", "BOA", "Classes", "Class " + code]))
    }
    for band in bands {
      let slug = SportsResolver.normalize(band.name).replacingOccurrences(of: " ", with: "-")
      let name = band.name + " (" + band.state + ") Marching Band"
      let expanded = band.name.replacingOccurrences(of: "HS", with: "High School")
      result.append(.init(id: SportsReviewedCatalog.id("team:boa:" + band.state.lowercased() + ":" + slug),
        name: name, kind: "team", sportID: sport, competitionIDs: [grandNationals, boa],
        aliases: [band.name, expanded], division: "2026 Grand Nationals Participant",
        groupPath: ["Marching Arts", "BOA", "Bands", band.state]))
    }
    return result
  }
}
