import type { GapInvestigation, GapInvestigationEvidence, MetricRollup, Overview } from "@/lib/operations-types"

const now = new Date()
const iso = (secondsAgo = 0) => new Date(now.getTime() - secondsAgo * 1000).toISOString()

const demoCollections = [
  { name: "site.standard.document", rates: [512, 78, 3], latency: 0.22, lag: 2.1 },
  { name: "site.standard.entry", rates: [1264, 193, 6], latency: 0.31, lag: 1.6 },
  { name: "app.skyreader.feed.subscription", rates: [852, 41, 1], latency: 0.19, lag: 1.1 },
] as const

export function demoMetricRollups(reference = new Date()): MetricRollup[] {
  const lastCompletedMinute = Math.floor(reference.getTime() / 60_000) * 60_000 - 60_000
  return demoCollections.flatMap((collection, collectionIndex) =>
    Array.from({ length: 15 }, (_, minuteIndex) => {
      const bucketStart = new Date(lastCompletedMinute - (14 - minuteIndex) * 60_000).toISOString()
    const variation = 1 + Math.sin(minuteIndex * (0.45 + collectionIndex * 0.08) + collectionIndex) * 0.12
    const operations = ["create", "update", "delete"] as const
    const operationRollups = operations.flatMap((operation, operationIndex): MetricRollup[] => {
      const sampleCount = Math.max(1, Math.round(collection.rates[operationIndex] * variation * 60))
      const duration = collection.latency * (1 + Math.cos(minuteIndex * 0.37 + operationIndex) * 0.18)
      const dimensions = { collection: collection.name, operation, ingestion_mode: "live" }
      return [
        {
          environment: "dev",
          bucketStart,
          metricName: "socialwire.ingestion.events_total",
          dimensions,
          sampleCount,
          valueSum: sampleCount,
          valueMin: 1,
          valueMax: 1,
        },
        {
          environment: "dev",
          bucketStart,
          metricName: "socialwire.ingestion.results_total",
          dimensions: { ...dimensions, result: "success" },
          sampleCount,
          valueSum: sampleCount,
          valueMin: 1,
          valueMax: 1,
        },
        {
          environment: "dev",
          bucketStart,
          metricName: "socialwire.ingestion.db_write_duration_seconds",
          dimensions,
          sampleCount,
          valueSum: sampleCount * duration,
          valueMin: duration * 0.55,
          valueMax: duration * 2.4,
        },
      ]
    })
    const totalSamples = operationRollups
      .filter(({ metricName }) => metricName === "socialwire.ingestion.events_total")
      .reduce((sum, rollup) => sum + rollup.sampleCount, 0)
    const lag = collection.lag * (1 + Math.sin(minuteIndex * 0.29 + collectionIndex) * 0.2)
    const lagRollup: MetricRollup = {
      environment: "dev",
      bucketStart,
      metricName: "socialwire.ingestion.commit_lag_seconds",
      dimensions: { collection: collection.name, ingestion_mode: "live" },
      sampleCount: totalSamples,
      valueSum: totalSamples * lag,
      valueMin: lag * 0.5,
      valueMax: lag * 1.8,
    }
    const failureRollups: MetricRollup[] =
      collectionIndex < 2 && minuteIndex % (7 + collectionIndex) === 3
        ? [
            {
              environment: "dev",
              bucketStart,
              metricName: "socialwire.ingestion.results_total",
              dimensions: {
                collection: collection.name,
                operation: "create",
                result: "error",
                ingestion_mode: "live",
              },
              sampleCount: collectionIndex + 1,
              valueSum: collectionIndex + 1,
              valueMin: 1,
              valueMax: 1,
            },
          ]
        : []
      return [...operationRollups, lagRollup, ...failureRollups]
    }).flat(),
  )
}

export const demoOverview: Overview = {
  services: ["gateway", "appview", "appview-worker", "operations"].map((service, index) => ({
    service,
    environment: "dev",
    instanceId: `dev-${service}-${index + 1}`,
    liveness: "healthy",
    readiness: "healthy",
    freshness: index === 2 ? "degraded" : "healthy",
    completeness: index === 1 ? "degraded" : "healthy",
    dependencyState: { database: "ready", internalTrust: "ready" },
    version: "sha-8f42c1d",
    startedAt: iso(184000),
    heartbeatAt: iso(6 + index),
  })),
  ingestion: {
    environment: "dev",
    source: "jetstream",
    connectionState: "connected",
    connectedAt: iso(224000),
    lastReceivedCursor: 1747488467123456,
    lastReceivedEventAt: iso(2.1),
    lastReceivedAt: iso(2),
    lastCommittedCursor: 1747488465023123,
    lastCommittedEventAt: iso(4.2),
    lastCommittedAt: iso(4),
    queueDepth: 128,
    transportHeartbeatAt: iso(1),
    heartbeatAt: iso(2),
    version: 7,
  },
  ingestionSources: [
    {
      environment: "dev",
      source: "tap-shadow",
      connectionState: "connected",
      connectedAt: iso(86_400),
      lastReceivedAt: iso(2),
      lastCommittedAt: iso(4),
      queueDepth: 0,
      transportHeartbeatAt: iso(1),
      heartbeatAt: iso(2),
      version: 4,
    },
    {
      environment: "dev",
      source: "rss-polling",
      connectionState: "connected",
      lastReceivedAt: iso(31),
      lastCommittedAt: iso(29),
      queueDepth: 0,
      transportHeartbeatAt: iso(3),
      heartbeatAt: iso(3),
      version: 2,
    },
    {
      environment: "dev",
      source: "projection-repair",
      connectionState: "connected",
      lastCommittedAt: iso(8),
      queueDepth: 2,
      transportHeartbeatAt: iso(2),
      heartbeatAt: iso(2),
      version: 3,
    },
    {
      environment: "dev",
      source: "cache-maintenance",
      connectionState: "connected",
      lastCommittedAt: iso(42),
      queueDepth: 0,
      transportHeartbeatAt: iso(3),
      heartbeatAt: iso(3),
      version: 1,
    },
  ],
  jetstreamEndpoints: [
    {
      id: "jetstream1.us-east.bsky.network",
      environment: "dev",
      displayName: "Jetstream 1",
      host: "jetstream1.us-east.bsky.network",
      role: "active",
      connectionState: "connected",
      lastConnectedAt: iso(224000),
      connectionAttempts: 3,
      failoverCount: 1,
      updatedAt: iso(2),
      version: 3,
    },
    {
      id: "jetstream2.us-east.bsky.network",
      environment: "dev",
      displayName: "Jetstream 2",
      host: "jetstream2.us-east.bsky.network",
      role: "standby",
      connectionState: "unknown",
      lastConnectedAt: iso(410000),
      lastDisconnectedAt: iso(224010),
      connectionAttempts: 2,
      failoverCount: 1,
      updatedAt: iso(224010),
      version: 2,
    },
  ],
  commands: [],
  gaps: [
    {
      id: "gap-20250516-001",
      environment: "dev",
      source: "jetstream",
      startCursor: 1747487745123000,
      endCursor: 1747487750123000,
      reason: "jetstream_disconnect",
      status: "confirmed",
      collections: [],
      detectedAt: iso(74000),
      updatedAt: iso(70000),
      discoveredCount: 1982341,
      processedCount: 0,
      failedCount: 0,
      reconciledCount: 0,
      version: 2,
    },
    {
      id: "gap-20250517-002",
      environment: "dev",
      source: "jetstream",
      startCursor: 1747488451121000,
      endCursor: 1747488455123000,
      reason: "consumer_restart",
      status: "suspected",
      collections: ["site.standard.document", "site.standard.entry"],
      detectedAt: iso(25000),
      updatedAt: iso(24000),
      discoveredCount: 182432,
      processedCount: 0,
      failedCount: 0,
      reconciledCount: 0,
      version: 1,
    },
    {
      id: "gap-20250515-003",
      environment: "dev",
      source: "jetstream",
      startCursor: 1747488129123000,
      endCursor: 1747488132123000,
      reason: "commit_stalled",
      status: "backfilling",
      collections: ["site.standard.entry"],
      detectedAt: iso(120000),
      updatedAt: iso(120),
      backfillJobId: "bf-20250517-001",
      discoveredCount: 1248932,
      processedCount: 774338,
      failedCount: 12,
      reconciledCount: 0,
      version: 5,
    },
    {
      id: "gap-20250514-004",
      environment: "dev",
      source: "jetstream",
      startCursor: 1747487651123000,
      endCursor: 1747487656123000,
      reason: "consumer_restart",
      status: "resolved",
      collections: ["app.skyreader.feed.subscription"],
      detectedAt: iso(172800),
      updatedAt: iso(82000),
      backfillJobId: "bf-20250516-005",
      discoveredCount: 512991,
      processedCount: 512991,
      failedCount: 0,
      reconciledCount: 512991,
      version: 7,
    },
  ],
  backfills: [
    {
      id: "bf-20250517-001",
      environment: "dev",
      gapId: "gap-20250515-003",
      sourceMode: "jetstream_replay",
      status: "running",
      startCursor: 1747488451123000,
      endCursor: 1747488455123000,
      checkpointCursor: 1747488454123456,
      collections: ["site.standard.entry"],
      authorDids: [],
      authorResults: [],
      batchSize: 1000,
      rateLimit: 500,
      maxConcurrency: 4,
      estimatedCount: 1982341,
      processedCount: 1248932,
      failedCount: 12,
      reconciledCount: 0,
      requestedByDid: "did:plc:operator",
      auditNote: "Recover confirmed disconnect gap",
      leaseOwner: "worker-dev-03",
      leaseExpiresAt: iso(-45),
      createdAt: iso(7200),
      updatedAt: iso(10),
      version: 8,
      verificationStatus: "required",
      verificationReason: "jetstream_unverified_source",
      scopeTruncated: false,
    },
    {
      id: "bf-20250517-002",
      environment: "dev",
      sourceMode: "jetstream_replay",
      status: "running",
      startCursor: 1747488436123000,
      endCursor: 1747488444123000,
      checkpointCursor: 1747488439123456,
      collections: ["site.standard.document"],
      authorDids: [],
      authorResults: [],
      batchSize: 1000,
      rateLimit: 400,
      maxConcurrency: 4,
      estimatedCount: 1013420,
      processedCount: 182442,
      failedCount: 2,
      reconciledCount: 0,
      requestedByDid: "did:plc:operator",
      auditNote: "Validate suspected gap",
      leaseOwner: "worker-dev-02",
      leaseExpiresAt: iso(-40),
      createdAt: iso(3600),
      updatedAt: iso(14),
      version: 6,
      verificationStatus: "required",
      verificationReason: "jetstream_unverified_source",
      scopeTruncated: false,
    },
    {
      id: "bf-20250516-005",
      environment: "dev",
      gapId: "gap-20250514-004",
      sourceMode: "pds_reconciliation",
      status: "completed",
      collections: ["app.skyreader.feed.subscription"],
      authorDids: ["did:plc:sample"],
      authorResults: [
        {
          did: "did:plc:sample",
          collection: "app.skyreader.feed.subscription",
          discoveredCount: 512991,
          processedCount: 512991,
          failedCount: 0,
          capped: false,
          truncated: false,
          status: "succeeded",
        },
      ],
      batchSize: 500,
      rateLimit: 250,
      maxConcurrency: 2,
      estimatedCount: 512991,
      processedCount: 512991,
      failedCount: 0,
      reconciledCount: 512991,
      requestedByDid: "did:plc:operator",
      auditNote: "Reconcile outside replay window",
      createdAt: iso(86400),
      updatedAt: iso(82000),
      completedAt: iso(82000),
      version: 4,
      verificationStatus: "required",
      verificationReason: "pds_historical_deletes_unprovable",
      scopeTruncated: false,
    },
    {
      id: "bf-20250516-006",
      environment: "dev",
      sourceMode: "jetstream_replay",
      status: "failed",
      startCursor: 1747487600123000,
      endCursor: 1747487605123000,
      checkpointCursor: 1747487601123000,
      collections: ["site.standard.document"],
      authorDids: [],
      authorResults: [],
      batchSize: 1000,
      rateLimit: 500,
      maxConcurrency: 4,
      estimatedCount: 1250,
      processedCount: 250,
      failedCount: 1,
      reconciledCount: 0,
      requestedByDid: "did:plc:operator",
      auditNote: "",
      failureReason: "database_timeout",
      createdAt: iso(90000),
      updatedAt: iso(89900),
      completedAt: iso(89900),
      version: 3,
      verificationStatus: "failed",
      verificationReason: "recovery_failures",
      scopeTruncated: true,
    },
    {
      id: "bf-demo-no-matches",
      environment: "dev",
      sourceMode: "jetstream_replay",
      status: "completed",
      startCursor: 1747456593925382,
      endCursor: 1747459397244042,
      collections: ["site.standard.document"],
      authorDids: [],
      authorResults: [],
      batchSize: 1000,
      rateLimit: 500,
      maxConcurrency: 1,
      estimatedCount: 127,
      processedCount: 0,
      failedCount: 0,
      reconciledCount: 0,
      requestedByDid: "did:plc:operator",
      auditNote: "Verify a completed scan with no matching records",
      createdAt: iso(120),
      updatedAt: iso(60),
      completedAt: iso(60),
      version: 2,
      verificationStatus: "required",
      verificationReason: "jetstream_unverified_source",
      scopeTruncated: false,
    },
  ],
  alerts: [
    {
      id: "alert-001",
      environment: "dev",
      rule: "confirmed_unresolved_gap",
      conditionKey: "gap:gap-20250516-001",
      severity: "critical",
      status: "open",
      summary: "A confirmed ingestion gap requires recovery",
      evidence: { gap_id: "gap-20250516-001", duration_us: "5000000" },
      runbookSlug: "confirming-and-scoping-a-gap",
      openedAt: iso(70000),
      updatedAt: iso(70000),
      deliveryAttempts: 1,
      version: 2,
    },
    {
      id: "alert-002",
      environment: "dev",
      rule: "commit_cursor_stale",
      conditionKey: "stream:jetstream:commit_cursor_stale",
      severity: "warning",
      status: "acknowledged",
      summary: "Committed cursor freshness exceeded five minutes",
      evidence: { age_seconds: "322" },
      runbookSlug: "live-process-stalled-ingestion",
      openedAt: iso(9000),
      updatedAt: iso(8000),
      acknowledgedByDid: "did:plc:operator",
      deliveryAttempts: 2,
      version: 3,
    },
  ],
  recentTraces: [
    ["gateway.request", 812, "ok", "/v1/appview/bootstrap-stream"],
    ["appview.request", 286, "ok", "/v1/appview/entries"],
    ["appview.cache.lookup", 95, "ok", "/v1/appview/unread-counts"],
    ["gateway.appview.proxy", 143, "ok", "/v1/publications/sidebar"],
    ["worker.index.commit", 1210, "error", "site.standard.entry"],
  ].map(([name, duration, status, route], index) => ({
    id: `span-${index}`,
    environment: "dev",
    traceId: `e2f3a4b5c6d7890${index}`.padEnd(32, "a"),
    service: String(name).split(".")[0],
    name: String(name),
    startedAt: iso(20 + index * 8),
    durationMs: Number(duration),
    status: String(status),
    attributes: {
      route_template: String(route),
      method: "GET",
      status_class: status === "error" ? "5xx" : "2xx",
      environment: "dev",
      ...(index === 2 ? { query_name: "overview" } : {}),
    },
    expiresAt: iso(-604800),
  })),
  metricRollups: demoMetricRollups(now),
  database: {
    databaseSizeBytes: 3_006_477_312,
    activeConnections: 8,
    maxConnections: 15,
    transactionsTotal: 4_826_341,
    estimatedRecords: 9_842_117,
    cacheHitRatio: 0.997,
    statsResetAt: iso(604800),
    topTables: [
      { schema: "public", table: "content_items", estimatedRecords: 6_482_193 },
      { schema: "public", table: "appview_read_marks", estimatedRecords: 1_924_882 },
      { schema: "public", table: "appview_projection_caches", estimatedRecords: 842_117 },
      { schema: "public", table: "operations_trace_spans", estimatedRecords: 592_925 },
    ],
    connectedBackends: 8,
    activeQueries: 2,
    transactionRatePerSecond: 84.2,
    observedAt: iso(8),
    evidenceAgeSeconds: 8,
  },
  capabilities: {
    environment: "dev",
    telemetry: { enabled: true },
    recovery: { enabled: false, disabledReason: "Synthetic demo data is read-only" },
    recoveryModes: {
      tapVerifiedResync: {
        enabled: false,
        disabledReason: "Pinned Tap does not yet provide a safe resync endpoint with complete delete and watermark proof",
      },
      jetstreamReplay: { enabled: false, disabledReason: "Synthetic demo data is read-only" },
      pdsReconciliation: { enabled: false, disabledReason: "Synthetic demo data is read-only" },
    },
    alertDelivery: { enabled: false, disabledReason: "Synthetic demo data does not deliver alerts" },
    eventStream: {
      enabled: false,
      disabledReason: "Synthetic demo data does not expose an event transport",
      path: "/v1/operations/events/stream",
      retryMilliseconds: 1_000,
      fallbackPollMilliseconds: 2_500,
    },
    generatedAt: iso(),
  },
  counts: {
    activeGaps: 3,
    activeBackfills: 2,
    attentionBackfills: 1,
    completedBackfills: 2,
    unresolvedAlerts: 2,
  },
  evidence: {
    overview: {
      source: "Synthetic demo fixture",
      accuracy: "estimated",
      generatedAt: iso(),
      ageSeconds: 0,
      validUntil: iso(-60),
      coverage: 1,
      degradedReason: "Demo values are illustrative and do not describe a deployed service.",
    },
    services: {
      source: "Synthetic service heartbeat fixture",
      accuracy: "estimated",
      generatedAt: iso(),
      indexedThrough: iso(6),
      ageSeconds: 6,
      validUntil: iso(-45),
      coverage: 1,
      degradedReason: "Demo values are illustrative and do not describe deployed services.",
    },
    ingestion: {
      source: "Synthetic transport fixture",
      accuracy: "estimated",
      generatedAt: iso(),
      indexedThrough: iso(2),
      ageSeconds: 2,
      validUntil: iso(-45),
      coverage: 1,
      degradedReason: "Demo values are illustrative and do not describe a deployed transport.",
    },
    database: {
      source: "Synthetic PostgreSQL observation fixture",
      accuracy: "estimated",
      generatedAt: iso(),
      indexedThrough: iso(8),
      ageSeconds: 8,
      validUntil: iso(-60),
      coverage: 1,
      degradedReason: "Demo values are illustrative and do not describe a deployed database.",
    },
  },
  refreshedAt: iso(),
}

export function demoGapInvestigation(gapId: string): GapInvestigation {
  const gap = demoOverview.gaps!.find((candidate) => candidate.id === gapId) ?? demoOverview.gaps![0]!
  const disconnectedAt = new Date(gap.detectedAt).getTime() - 2_000
  const connectedAt = disconnectedAt + 8_000
  const evidence: GapInvestigationEvidence[] = [
    {
      id: "event-commit-failed",
      kind: "indexing",
      occurredAt: new Date(disconnectedAt - 400).toISOString(),
      service: "appview-worker",
      title: "Commit indexing failed",
      detail: "database_timeout",
      attributes: { collection: "site.standard.entry", error_type: "database_timeout" },
      traceId: "e2f3a4b5c6d78904".padEnd(32, "a"),
    },
    {
      id: "event-disconnected",
      kind: "stream",
      occurredAt: new Date(disconnectedAt).toISOString(),
      service: "appview-worker",
      title: "Jetstream disconnected",
      detail: "database_timeout",
      attributes: { error_type: "database_timeout" },
    },
    {
      id: "gap-detected",
      kind: "gap",
      occurredAt: gap.detectedAt,
      service: "jetstream",
      title: "Gap detected",
      detail: gap.reason.replaceAll("_", " "),
      attributes: {
        start_cursor: String(gap.startCursor ?? "unknown"),
        end_cursor: String(gap.endCursor ?? "unknown"),
      },
    },
    {
      id: "event-connected",
      kind: "stream",
      occurredAt: new Date(connectedAt).toISOString(),
      service: "appview-worker",
      title: "Jetstream connected",
      detail: "The worker established a Jetstream connection.",
      attributes: {},
    },
  ]
  evidence.sort((a, b) => a.occurredAt.localeCompare(b.occurredAt))
  return {
    gap,
    windowStart: new Date(disconnectedAt - 5 * 60_000).toISOString(),
    windowEnd: new Date(connectedAt + 10 * 60_000).toISOString(),
    assessment: {
      title: "Indexing failure interrupted commit advancement",
      confidence: "high",
      summary: "The worker recorded a database timeout immediately before the Jetstream connection was restarted.",
      evidenceIds: ["event-commit-failed", "event-disconnected"],
      limitations: [
        "This assessment correlates recorded signals; it cannot prove an unobserved upstream or infrastructure root cause.",
        "Error details are deliberately redacted to a bounded category in operations telemetry.",
      ],
    },
    evidence,
    recommendedActions: [
      "Open the correlated error trace and inspect its recorded attributes.",
      "Verify the proposed recovery scope against the gap cursor range before running a backfill.",
    ],
  }
}
