const method = (name: string) => `/xrpc/app.thesocialwire.operations.${name}`

export const operationsXrpc = {
  getCapabilities: method("getCapabilities"),
  getOverview: method("getOverview"),
  listServices: method("listServices"),
  getIngestion: method("getIngestion"),
  listIngestionEndpoints: method("listIngestionEndpoints"),
  listCommands: method("listCommands"),
  getAppView: method("getAppView"),
  listGaps: method("listGaps"),
  getGapInvestigation: method("getGapInvestigation"),
  listBackfills: method("listBackfills"),
  getBackfill: method("getBackfill"),
  listAlerts: method("listAlerts"),
  listMetrics: method("listMetrics"),
  listTraces: method("listTraces"),
  getTrace: method("getTrace"),
  reconnectIngestion: method("reconnectIngestion"),
  updateGap: method("updateGap"),
  dryRunBackfill: method("dryRunBackfill"),
  createBackfill: method("createBackfill"),
  pauseBackfill: method("pauseBackfill"),
  resumeBackfill: method("resumeBackfill"),
  cancelBackfill: method("cancelBackfill"),
  acknowledgeAlert: method("acknowledgeAlert"),
  resolveAlert: method("resolveAlert"),
  retryAlert: method("retryAlert"),
} as const
