package gateway

import "strings"

const webScope = "repo:app.thesocialwire.readState?action=create&action=update&action=delete repo:app.thesocialwire.readStateChunk?action=create&action=update&action=delete atproto repo:app.thesocialwire.folder?action=create&action=update&action=delete repo:app.thesocialwire.publicationPrefs?action=create&action=update&action=delete repo:app.thesocialwire.preferences?action=create&action=update&action=delete repo:app.thesocialwire.finance.selection?action=create&action=update&action=delete repo:app.thesocialwire.sports.selection?action=create&action=update&action=delete repo:com.thesocialwire.folder?action=create&action=update&action=delete repo:com.thesocialwire.publicationPrefs?action=create&action=update&action=delete repo:com.thesocialwire.preferences?action=create&action=update&action=delete include:app.bsky.authCreatePosts?aud=did:web:api.bsky.app%23bsky_appview include:app.bsky.authDeleteContent?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.actor.getPreferences?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.graph.getBlocks?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.graph.getMutes?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.graph.getListMutes?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.graph.getListBlocks?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.graph.getList?aud=did:web:api.bsky.app%23bsky_appview repo:app.bsky.feed.like?action=create repo:app.bsky.feed.repost?action=create repo:community.lexicon.bookmarks.bookmark?action=create&action=update&action=delete include:link.latr.authFull repo:link.latr.saved.external?action=delete repo:link.latr.saved.item?action=delete repo:com.latr.saved.external?action=delete repo:com.latr.saved.item?action=delete repo:network.cosmik.card?action=create&action=update&action=delete repo:network.cosmik.collection?action=create&action=update&action=delete repo:network.cosmik.collectionLink?action=create&action=update&action=delete repo:network.cosmik.collectionLinkRemoval?action=create&action=update&action=delete repo:network.cosmik.connection?action=create&action=update&action=delete repo:app.thesocialwire.wireFeedback?action=create&action=update&action=delete include:site.standard.authSocial repo:app.skyreader.feed.subscription?action=create&action=update&action=delete repo:app.standard-reader.listSave?action=create&action=update&action=delete repo:app.standard-reader.list?action=create&action=delete include:app.userinput.authFull blob:*/* repo:app.thesocialwire.podcast.clip?action=create&action=update&action=delete"
const iosScope = "atproto repo:app.thesocialwire.readState?action=create&action=update repo:app.thesocialwire.readStateChunk?action=create&action=update&action=delete repo:app.thesocialwire.folder?action=create&action=update&action=delete repo:app.thesocialwire.publicationPrefs?action=create&action=update&action=delete repo:app.thesocialwire.preferences?action=create&action=update&action=delete repo:com.thesocialwire.folder?action=create&action=update&action=delete repo:com.thesocialwire.publicationPrefs?action=create&action=update&action=delete repo:com.thesocialwire.preferences?action=create&action=update&action=delete include:app.bsky.authCreatePosts?aud=did:web:api.bsky.app%23bsky_appview include:app.bsky.authDeleteContent?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.actor.getPreferences?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.graph.getBlocks?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.graph.getMutes?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.graph.getListMutes?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.graph.getListBlocks?aud=did:web:api.bsky.app%23bsky_appview rpc:app.bsky.graph.getList?aud=did:web:api.bsky.app%23bsky_appview repo:app.bsky.feed.like?action=create repo:app.bsky.feed.repost?action=create repo:community.lexicon.bookmarks.bookmark?action=create&action=update&action=delete include:link.latr.authFull repo:link.latr.saved.external?action=delete repo:link.latr.saved.item?action=delete repo:com.latr.saved.external?action=delete repo:com.latr.saved.item?action=delete repo:network.cosmik.card?action=create&action=update&action=delete repo:network.cosmik.collection?action=create&action=update&action=delete repo:network.cosmik.collectionLink?action=create&action=update&action=delete repo:network.cosmik.collectionLinkRemoval?action=create&action=update&action=delete repo:network.cosmik.connection?action=create&action=update&action=delete repo:app.thesocialwire.finance.selection?action=create&action=update&action=delete repo:app.thesocialwire.sports.selection?action=create&action=update&action=delete repo:app.standard-reader.list?action=create&action=delete repo:app.standard-reader.listSave?action=create&action=update&action=delete repo:app.thesocialwire.wireFeedback?action=create&action=update&action=delete include:site.standard.authSocial repo:app.skyreader.feed.subscription?action=create&action=update&action=delete repo:app.thesocialwire.podcast.clip?action=create&action=update&action=delete include:app.userinput.authFull blob:*/* repo:site.standard.graph.subscription?action=create&action=update&action=delete repo:app.bsky.feed.post?action=update"

// podcastScope preserves the established permission ordering when enabled and
// the exact pre-podcast metadata contract when the feature is disabled.
func podcastScope(scope string, enabled bool) string {
	if enabled {
		return scope
	}
	fields := strings.Fields(scope)
	kept := fields[:0]
	for _, field := range fields {
		if field != "repo:app.thesocialwire.podcast.clip?action=create&action=update&action=delete" {
			kept = append(kept, field)
		}
	}
	return strings.Join(kept, " ")
}
