package sportscore

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"
	"time"
)

// These fixtures were generated by the reference Swift provider using its
// ISO8601 JSON encoder, covering provider statuses, clock fallbacks and timestamps.
func TestProviderEventSwiftConformance(t *testing.T) {
	data, err := os.ReadFile("provider_fixtures.json")
	if err != nil {
		t.Fatal(err)
	}
	var cases []struct {
		Row   map[string]string `json:"row"`
		Event json.RawMessage   `json:"event"`
	}
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatal(err)
	}
	for i, fixture := range cases {
		got := ProviderEvent(fixture.Row, "league", nil, time.Unix(1791244800, 0))
		var wantJSON, gotJSON any
		if len(fixture.Event) != 0 {
			if err := json.Unmarshal(fixture.Event, &wantJSON); err != nil {
				t.Fatal(err)
			}
		}
		encoded, err := json.Marshal(got)
		if err != nil {
			t.Fatal(err)
		}
		if err := json.Unmarshal(encoded, &gotJSON); err != nil {
			t.Fatal(err)
		}
		if !reflect.DeepEqual(wantJSON, gotJSON) {
			t.Errorf("case %d row %v: got %s want %s", i, fixture.Row, encoded, fixture.Event)
		}
	}
}
