import { afterAll, afterEach, beforeAll, beforeEach, expect, it, spyOn } from "bun:test";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { IDBFactory } from "fake-indexeddb";
import type { OAuthSession } from "@atproto/oauth-client-browser";
import * as Auth from "@/hooks/useAuth";
import * as Publishing from "@/lib/articles/articlePublishingClient";
import { listArticleDrafts } from "@/lib/articles/articleDraftStorage";
import { ArticlesWorkspace } from "@/components/Articles/ArticlesWorkspace";
import { SidebarProvider } from "@/components/ui/sidebar";
const did = "did:plc:abcdefghijklmnopqrstuvwx";
let client: QueryClient;
const restores: (() => void)[] = [];
const originalMatchMedia = Object.getOwnPropertyDescriptor(window, "matchMedia");
const originalIDB = Object.getOwnPropertyDescriptor(globalThis, "indexedDB");
beforeAll(() => { Object.defineProperty(window, "matchMedia", { configurable: true, value: () => ({ matches: false, addEventListener() {}, removeEventListener() {} }) }); });
afterAll(() => { if (originalMatchMedia) Object.defineProperty(window, "matchMedia", originalMatchMedia); else Reflect.deleteProperty(window, "matchMedia"); });
beforeEach(() => {
  Object.defineProperty(globalThis, "indexedDB", { configurable: true, value: new IDBFactory() });
  client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: Infinity } } });
  const auth = spyOn(Auth, "useAuth").mockReturnValue({ session: { did }, getOAuthSession: () => ({ did } as unknown as OAuthSession), oauthSessionReloadSeq: 0 } as ReturnType<typeof Auth.useAuth>); restores.push(() => auth.mockRestore());
  const pubs = spyOn(Publishing, "listArticlePublications").mockResolvedValue([{ uri: `at://${did}/site.standard.publication/one`, cid: "pub", name: "Test Publication", url: "https://publication.test", host: "leaflet", record: {} }]); restores.push(() => pubs.mockRestore());
  const history = spyOn(Publishing, "listPublishedArticles").mockResolvedValue([]); restores.push(() => history.mockRestore());
});
afterEach(() => { cleanup(); client.clear(); restores.splice(0).reverse().forEach(restore => restore()); if (originalIDB) Object.defineProperty(globalThis, "indexedDB", originalIDB); else Reflect.deleteProperty(globalThis, "indexedDB"); });
it("keeps a newly entered title through immediate mode changes, body edits, Save Draft, and Preview", async () => {
  await act(async () => { render(<QueryClientProvider client={client}><SidebarProvider><ArticlesWorkspace /></SidebarProvider></QueryClientProvider>); });
  await waitFor(() => expect((screen.getByRole("button", { name: "New Article" }) as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(screen.getByRole("button", { name: "New Article" }));
  const title = await screen.findByLabelText("Article Title");
  fireEvent.change(title, { target: { value: "Retained New Article Title" } });
  fireEvent.click(screen.getByRole("button", { name: "Markdown" }));
  fireEvent.change(screen.getByLabelText("Article Markdown"), { target: { value: "# A New Body\n\nSaved Article Content." } });
  fireEvent.click(screen.getByRole("button", { name: "Save Draft" }));
  await waitFor(async () => {
    const rows = await listArticleDrafts(did);
    expect(rows).toHaveLength(1);
    expect(rows[0]).toMatchObject({ title: "Retained New Article Title", markdown: "# A New Body\n\nSaved Article Content." });
  });
  await waitFor(() => expect((screen.getByRole("button", { name: "Save Draft" }) as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(screen.getByRole("button", { name: "Preview" }));
  expect((screen.getByLabelText("Article Title") as HTMLInputElement).value).toBe("Retained New Article Title");
  expect(screen.getByText("Saved Article Content.")).toBeTruthy();
  expect(screen.getByRole("button", { name: "Retained New Article Title" })).toBeTruthy();
  cleanup(); client.clear();
  await act(async () => { render(<QueryClientProvider client={client}><SidebarProvider><ArticlesWorkspace /></SidebarProvider></QueryClientProvider>); });
  const restored = await screen.findByLabelText("Article Title");
  expect((restored as HTMLInputElement).value).toBe("Retained New Article Title");
  fireEvent.click(screen.getByRole("button", { name: "Markdown" }));
  expect((screen.getByLabelText("Article Markdown") as HTMLTextAreaElement).value).toBe("# A New Body\n\nSaved Article Content.");
});
