import { afterEach, beforeAll, describe, expect, it } from "bun:test";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { FinanceFollowingSidebar } from "@/components/FinanceFollowingSidebar";
import type { FinanceFeedDefinition, FinanceSelection } from "@/lib/financeFeedClient";
beforeAll(()=>{for(const name of ["HTMLElement","Element","Node","DOMRect"] as const)Object.defineProperty(globalThis,name,{configurable:true,value:window[name]});});
afterEach(cleanup);
const definitions:FinanceFeedDefinition[]=[{id:"instrument:apple",title:"Apple · AAPL · Nasdaq Stock Market (NASDAQ)",kind:"instrument",instrumentIDs:["apple"],sectorIDs:[],description:"Apple"},{id:"instrument:msft",title:"Microsoft · MSFT · NASDAQ",kind:"instrument",instrumentIDs:["msft"],sectorIDs:[],description:"Microsoft"},{id:"industry:tech",title:"Technology",kind:"industry",instrumentIDs:[],sectorIDs:["tech"],description:"Tech"}];
const selections:FinanceSelection[]=[{kind:"instrument",reference:"apple",createdAt:"now",updatedAt:"now"},{kind:"instrument",reference:"unknown",createdAt:"now",updatedAt:"now"},{kind:"sector",reference:"tech",createdAt:"now",updatedAt:"now"}];
describe("Followed securities",()=>{
 it("shows only catalog-backed followed securities and preserves shareable links",()=>{render(<FinanceFollowingSidebar definitions={definitions} selections={selections} feedID="instrument:apple"/>);const row=screen.getByRole("link",{name:"Apple · AAPL · Nasdaq Stock Market (NASDAQ)"});expect(row.getAttribute("href")).toBe("/read?feed=finance&financeFeed=instrument%3Aapple");expect(row.getAttribute("aria-current")).toBe("page");expect(screen.queryByRole("link",{name:/Microsoft/})).toBeNull();expect(screen.queryByRole("link",{name:"Technology"})).toBeNull();expect(screen.getByRole("link",{name:"All Finance"}).getAttribute("href")).toBe("/read?feed=finance");});
 it("uses in-place feed navigation for primary clicks",()=>{const changed:string[]=[];render(<FinanceFollowingSidebar definitions={definitions} selections={selections} feedID="finance" onFeedChange={id=>changed.push(id)}/>);fireEvent.click(screen.getByRole("link",{name:"Apple · AAPL · Nasdaq Stock Market (NASDAQ)"}));expect(changed).toEqual(["instrument:apple"]);});
 it("distinguishes loading and failed reconciliation from empty interests",()=>{const view=render(<FinanceFollowingSidebar definitions={definitions} selections={[]} feedID="finance" loading/>);expect(screen.getByText("Loading Your Securities…")).toBeTruthy();expect(screen.queryByText(/Add securities/)).toBeNull();view.rerender(<FinanceFollowingSidebar definitions={definitions} selections={[]} feedID="finance" error/>);expect(screen.getByText(/could not load/)).toBeTruthy();expect(screen.queryByText(/Add securities/)).toBeNull();});
});
