import { afterEach, describe, expect, it, spyOn } from "bun:test";
import { cleanup, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { FinanceInstrumentOverview } from "@/components/FinanceInstrumentOverview";
import * as Finance from "@/lib/financeFeedClient";
const feed: Finance.FinanceFeedDefinition = {id:"instrument:apple",title:"Apple · AAPL · NASDAQ",kind:"instrument",instrumentIDs:["apple"],sectorIDs:[],description:"Apple reporting"};
const instrument: Finance.FinanceInstrument={id:"apple",name:"Apple",symbol:"AAPL",kind:"equity",exchange:"NASDAQ",exchangeName:"Nasdaq Stock Market",tradingViewSymbol:"NASDAQ:AAPL"};
const restores:(()=>void)[]=[];
afterEach(()=>{cleanup();restores.splice(0).forEach(restore=>restore());});
function item(id:string,materiality:string,instrumentID="apple",confidenceBps=9500):Finance.FinanceItem {return {materiality,story:{itemId:id,canonicalUrl:`https://publisher.example/${id}`,title:`${id} Article`,source:{name:"Publisher",domain:"publisher.example"},reasons:[],provenance:[]},instruments:[{instrument:{...instrument,id:instrumentID},confidenceBps,prominence:1}],sectorIDs:[],majorGlobal:false};}
function mount(items:Finance.FinanceItem[],hidden=false){const client=new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0}}});restores.push(()=>client.clear());return render(<QueryClientProvider client={client}><FinanceInstrumentOverview feed={feed} items={items} hidden={hidden} widgetsEnabled={false}/></QueryClientProvider>);}
describe("Finance security overview",()=>{
 it("uses canonical association identity and labels earnings/filings as reporting",()=>{mount([item("Earnings","earnings"),item("Report","filing"),item("Routine","reporting"),item("Other","earnings","other"),item("Weak","earnings","apple",8000)]);expect(screen.getByText("Apple · AAPL · Nasdaq Stock Market (NASDAQ)")).toBeTruthy();expect(screen.getByRole("link",{name:"Earnings Article"}).getAttribute("href")).toBe("https://publisher.example/Earnings");expect(screen.getByRole("link",{name:"Report Article"})).toBeTruthy();expect(screen.queryByRole("link",{name:"Routine Article"})).toBeNull();expect(screen.queryByRole("link",{name:"Other Article"})).toBeNull();expect(screen.queryByRole("link",{name:"Weak Article"})).toBeNull();expect(screen.getByText(/Verified company report and earnings-call links are not available/)).toBeTruthy();});
 it("resolves no-story metadata only by exact canonical identity",async()=>{const search=spyOn(Finance,"searchFinanceInstruments").mockResolvedValue({instruments:[{...instrument,id:"wrong",name:"Different Apple"}]});restores.push(()=>search.mockRestore());mount([]);await waitFor(()=>expect(screen.getByText("Additional security details are unavailable.")).toBeTruthy());expect(screen.queryByText(/Different Apple/)).toBeNull();expect(search.mock.calls[0][0]).toBe("apple");});
 it("hydrates the exact listing without articles even when ticker matches collide",async()=>{const search=spyOn(Finance,"searchFinanceInstruments").mockResolvedValue({instruments:[{...instrument,id:"another-listing",exchange:"US",exchangeName:"United States Composite"},{...instrument,exchange:"RO",exchangeName:"Romania Composite"}]});restores.push(()=>search.mockRestore());mount([]);await waitFor(()=>expect(screen.getByText("Apple · AAPL · Romania Composite (RO)")).toBeTruthy());expect(search.mock.calls[0][0]).toBe("apple");expect(screen.queryByText(/United States Composite/)).toBeNull();});
 it("hides performance but keeps reporting links",()=>{mount([item("Earnings","earnings")],true);expect(screen.getByText("Performance data is hidden.")).toBeTruthy();expect(screen.getByRole("link",{name:"Earnings Article"})).toBeTruthy();});
 it("rejects non-HTTPS coverage URLs",()=>{const unsafe=item("Unsafe","filing");unsafe.story.canonicalUrl="javascript:alert(1)";mount([unsafe]);expect(screen.queryByRole("link",{name:"Unsafe Article"})).toBeNull();});
});
