import { afterAll, afterEach, beforeAll, beforeEach, expect, it, spyOn } from "bun:test";
import { cleanup, fireEvent, render, screen, waitFor, act } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { ReactNode } from "react";
import type { AppBskyFeedDefs, AppBskyGraphDefs, ModerationOpts } from "@atproto/api";
import type { OAuthSession } from "@atproto/oauth-client-browser";
import * as Auth from "@/hooks/useAuth";
import * as Catalog from "@/lib/blueskySocialClient";
import * as Lists from "@/lib/socialListsClient";
import * as Feeds from "@/lib/socialFeedDirectoryClient";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SocialLists } from "@/components/Social/SocialLists";
import { SocialFeedDirectory } from "@/components/Social/SocialFeedDirectory";
const browserGlobals = ["requestAnimationFrame", "cancelAnimationFrame", "getComputedStyle"] as const;
const originalBrowserGlobals = browserGlobals.map(name => [name, Object.getOwnPropertyDescriptor(globalThis, name)] as const);
beforeAll(() => {
  Object.defineProperty(globalThis, "requestAnimationFrame", { configurable: true, value: (callback: FrameRequestCallback) => setTimeout(() => callback(performance.now()), 0) });
  Object.defineProperty(globalThis, "cancelAnimationFrame", { configurable: true, value: (handle: ReturnType<typeof setTimeout>) => clearTimeout(handle) });
  Object.defineProperty(globalThis, "getComputedStyle", { configurable: true, value: window.getComputedStyle.bind(window) });
});
afterAll(async () => { await new Promise(resolve => setTimeout(resolve, 10)); for (const [name, descriptor] of originalBrowserGlobals) { if (descriptor) Object.defineProperty(globalThis, name, descriptor); else Reflect.deleteProperty(globalThis, name); } });
const did = "did:plc:alice";
const safety: ModerationOpts = { userDid: did, prefs: { adultContentEnabled: false, labels: {}, labelers: [], mutedWords: [], hiddenPosts: [] } };
const list: AppBskyGraphDefs.ListView = { uri: `at://${did}/app.bsky.graph.list/a`, cid: "bafyreia", creator: { did, handle: "alice.example" }, name: "Friends", purpose: "app.bsky.graph.defs#curatelist", indexedAt: "2026-10-10T00:00:00Z" };
const feed: AppBskyFeedDefs.GeneratorView = { uri: "at://did:plc:author/app.bsky.feed.generator/a", cid: "bafyreia", did: "did:plc:service", creator: { did: "did:plc:author", handle: "author.example" }, displayName: "Science Feed", indexedAt: "2026-10-10T00:00:00Z" };
let queryClient: QueryClient;
const restores: (() => void)[] = [];
function restore<T extends { mockRestore(): void }>(spy: T): T { restores.push(() => spy.mockRestore()); return spy; }
function Wrapper({ children }: { children: ReactNode }) { return <QueryClientProvider client={queryClient}><SidebarProvider>{children}</SidebarProvider></QueryClientProvider>; }
beforeEach(() => {
  const media = Object.getOwnPropertyDescriptor(window, "matchMedia");
  Object.defineProperty(window, "matchMedia", { configurable: true, value: () => ({ matches: false, addEventListener() {}, removeEventListener() {} }) });
  restores.push(() => { if (media) Object.defineProperty(window, "matchMedia", media); else Reflect.deleteProperty(window, "matchMedia"); });
  queryClient = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: Infinity } } });
  restore(spyOn(Auth, "useAuth").mockReturnValue({ session: { did }, getOAuthSession: () => ({ did } as unknown as OAuthSession), oauthSessionReloadSeq: 0 } as unknown as ReturnType<typeof Auth.useAuth>));
  restore(spyOn(Catalog, "getBlueskySocialCatalog").mockResolvedValue({ feeds: [], moderation: safety }));
});
afterEach(() => { cleanup(); queryClient.clear(); restores.splice(0).reverse().forEach(done => done()); });
it("Lists opens real details and the timeline, confirms deletion before writing", async () => {
  restore(spyOn(Lists, "getSocialLists").mockResolvedValue({ lists: [list] }));
  restore(spyOn(Lists, "getSocialList").mockResolvedValue({ list, items: [] }));
  const deleted = restore(spyOn(Lists, "deleteSocialList").mockResolvedValue(undefined));
  render(<SocialLists />, { wrapper: Wrapper });
  fireEvent.click(await screen.findByRole("button", { name: "Friends" }));
  const link = await screen.findByRole("link", { name: "Open List Feed" });
  expect(link.getAttribute("href")).toBe(Catalog.socialFeedHref({ kind: "list", uri: list.uri, name: list.name, pinned: false }));
  fireEvent.click(screen.getByRole("button", { name: "Delete List" }));
  await screen.findByRole("dialog");
  expect(deleted).not.toHaveBeenCalled();
  fireEvent.click(screen.getAllByRole("button", { name: "Delete List" }).at(-1)!);
  await waitFor(() => expect(deleted).toHaveBeenCalledTimes(1));
  expect(deleted.mock.calls[0][0].did).toBe(did);
});
it("List browse and directory hide blocked content and fail closed after moderation errors", async () => {
  restore(spyOn(Lists, "getSocialLists").mockResolvedValue({ lists: [{ ...list, creator: { ...list.creator, did: "did:plc:blocked", viewer: { blocking: "at://did:plc:alice/app.bsky.graph.block/a" } } }] }));
  render(<SocialLists />, { wrapper: Wrapper });
  await waitFor(() => expect(Boolean(screen.queryByText("Loading lists…"))).toBe(false));
  expect(screen.queryByRole("button", { name: "Friends" })).toBeNull();
  cleanup();
  restore(spyOn(Feeds, "getSocialFeedDirectory").mockResolvedValue({ feeds: [feed, { ...feed, uri: `${feed.uri}blocked`, displayName: "Hidden Feed", creator: { ...feed.creator, viewer: { blocking: "at://did:plc:alice/app.bsky.graph.block/a" } } }] }));
  restore(spyOn(Feeds, "getSocialSavedGenerators").mockResolvedValue([]));
  const catalog = restore(spyOn(Catalog, "getBlueskySocialCatalog").mockResolvedValue({ feeds: [], moderation: safety }));
  render(<SocialFeedDirectory />, { wrapper: Wrapper });
  await screen.findByText("Science Feed"); expect(screen.queryByText("Hidden Feed")).toBeNull();
  catalog.mockRejectedValue(new Error("Safety refresh unavailable"));
  await act(async () => { await queryClient.invalidateQueries({ queryKey: ["blueskySocial", did, "catalog"] }); });
  await waitFor(() => expect(Boolean(screen.queryByText("Science Feed"))).toBe(false));
});
it("Feed directory searches, paginates, and sends real save/pin mutations", async () => {
  const fetch = restore(spyOn(Feeds, "getSocialFeedDirectory").mockImplementation(async (_session, query, cursor) => ({ feeds: [{ ...feed, uri: cursor ? `${feed.uri}second` : feed.uri, displayName: cursor ? "Second Feed" : query ? "Search Feed" : feed.displayName }], cursor: cursor ? undefined : "next" })));
  restore(spyOn(Feeds, "getSocialSavedGenerators").mockResolvedValue([]));
  const changed = restore(spyOn(Feeds, "changeSocialSavedFeed").mockResolvedValue(undefined));
  render(<SocialFeedDirectory />, { wrapper: Wrapper });
  await screen.findByText("Science Feed");
  fireEvent.change(screen.getByRole("textbox", { name: "Search Feeds" }), { target: { value: "science" } });
  fireEvent.click(screen.getByRole("button", { name: "Search" }));
  await screen.findByText("Search Feed");
  expect(fetch.mock.calls.some(call => call[1] === "science")).toBe(true);
  fireEvent.click(screen.getByRole("button", { name: "Save Feed" }));
  await waitFor(() => expect(changed).toHaveBeenCalledTimes(1));
  expect(changed.mock.calls[0].slice(1)).toEqual([feed.uri, "save"]);
  await waitFor(() => expect(screen.getByRole("button", { name: "Pin Feed" }).hasAttribute("disabled")).toBe(false));
  fireEvent.click(screen.getByRole("button", { name: "Pin Feed" }));
  await waitFor(() => expect(changed).toHaveBeenCalledTimes(2));
  expect(changed.mock.calls[1].slice(1)).toEqual([feed.uri, "pin"]);
  fireEvent.click(screen.getByRole("button", { name: "Load More" }));
  await screen.findByText("Second Feed");
});
it("workspace drafts and list selections reset when the active account changes", async () => {
  let viewer = did;
  restore(spyOn(Auth, "useAuth").mockImplementation(() => ({ session: { did: viewer }, getOAuthSession: () => ({ did: viewer } as unknown as OAuthSession), oauthSessionReloadSeq: 0 } as unknown as ReturnType<typeof Auth.useAuth>)));
  restore(spyOn(Catalog, "getBlueskySocialCatalog").mockImplementation(async session => ({ feeds: [], moderation: { ...safety, userDid: session.did } })));
  restore(spyOn(Feeds, "getSocialFeedDirectory").mockResolvedValue({ feeds: [] }));
  restore(spyOn(Feeds, "getSocialSavedGenerators").mockResolvedValue([]));
  const { rerender, unmount } = render(<SocialFeedDirectory />, { wrapper: Wrapper });
  fireEvent.change(screen.getByRole("textbox", { name: "Search Feeds" }), { target: { value: "private draft" } });
  viewer = "did:plc:bob"; rerender(<SocialFeedDirectory />);
  expect((screen.getByRole("textbox", { name: "Search Feeds" }) as HTMLInputElement).value).toBe("");
  unmount(); viewer = did;
  restore(spyOn(Lists, "getSocialLists").mockResolvedValue({ lists: [list] }));
  restore(spyOn(Lists, "getSocialList").mockResolvedValue({ list, items: [] }));
  const listRender = render(<SocialLists />, { wrapper: Wrapper });
  fireEvent.click(await screen.findByRole("button", { name: "Friends" }));
  await screen.findByRole("link", { name: "Open List Feed" });
  fireEvent.change(screen.getByRole("textbox", { name: "Member Handle Or DID" }), { target: { value: "private member" } });
  viewer = "did:plc:bob"; listRender.rerender(<SocialLists />);
  expect(Boolean(screen.queryByRole("link", { name: "Open List Feed" }))).toBe(false);
  expect(Boolean(screen.queryByRole("textbox", { name: "Member Handle Or DID" }))).toBe(false);
});
