import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { afterAll, beforeAll, afterEach, expect, it, spyOn } from "bun:test";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import SportsExperience from "@/components/SportsExperience";
import * as Hooks from "@/hooks/useSportsFeed";
import * as Preferences from "@/hooks/useFeedDisplayPreferences";
import * as Picker from "@/components/SportsFeedPicker";
import type { SportsPickerFeedDefinition } from "@/lib/sportsFeedPickerGroups";
import * as Customize from "@/components/SportsCustomize";
import { DEFAULT_FEED_DISPLAY_PREFERENCES } from "@/lib/feedPreferences";
const globalKeys=["DOMRect","Element","HTMLElement","Node","getComputedStyle","requestAnimationFrame","cancelAnimationFrame"] as const;
const originals=new Map(globalKeys.map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)]));
beforeAll(()=>{
 const values={DOMRect:window.DOMRect,Element:window.Element,HTMLElement:window.HTMLElement,Node:window.Node,getComputedStyle:window.getComputedStyle.bind(window),requestAnimationFrame:(callback:FrameRequestCallback)=>setTimeout(()=>callback(performance.now()),0),cancelAnimationFrame:(handle:ReturnType<typeof setTimeout>)=>clearTimeout(handle)};
 for(const key of globalKeys)Object.defineProperty(globalThis,key,{configurable:true,writable:true,value:values[key]});
});
afterAll(()=>{for(const key of globalKeys){const original=originals.get(key);if(original)Object.defineProperty(globalThis,key,original);else Reflect.deleteProperty(globalThis,key);}});
const restores:(()=>void)[]=[];
afterEach(()=>{cleanup();for(const restore of restores.splice(0))restore();});
it("shows pending score saves and exposes preference write errors",async()=>{
 const feed=spyOn(Hooks,"useSportsFeed").mockReturnValue({signedIn:true,items:[],selections:[],catalog:{data:{entities:[],feeds:[]}},feed:{hasNextPage:false},isLoading:false,error:null} as unknown as ReturnType<typeof Hooks.useSportsFeed>);
 const customize=spyOn(Customize,"SportsCustomize").mockImplementation(()=><></>);
 const state={preferences:DEFAULT_FEED_DISPLAY_PREFERENCES,setHideSportsScores:()=>{},isLoading:false,isPending:true,error:null} as unknown as ReturnType<typeof Preferences.useFeedDisplayPreferences>;
 const prefs=spyOn(Preferences,"useFeedDisplayPreferences").mockReturnValue(state);
 restores.push(()=>feed.mockRestore(),()=>customize.mockRestore(),()=>prefs.mockRestore());
 const mounted=render(<SportsExperience/>);
 expect(screen.getByRole("status").textContent).toBe("Saving Score Preference…");
 fireEvent.click(screen.getByRole("button",{name:"Sports Options"}));
 await waitFor(()=>expect(screen.getByRole("menuitemcheckbox",{name:"Hide Scores"}).getAttribute("aria-disabled")).toBe("true"));
 prefs.mockReturnValue({...state,isPending:false,isLoading:true});
 mounted.rerender(<SportsExperience/>);
 expect(screen.getByRole("menuitemcheckbox",{name:"Hide Scores"}).getAttribute("aria-disabled")).toBe("true");
 prefs.mockReturnValue({...state,isPending:false,error:new Error("PDS Write Failed")});
 mounted.rerender(<SportsExperience/>);
 expect(screen.queryByRole("status")).toBeNull();
 expect(screen.getByRole("alert").textContent).toContain("Score preference could not save. PDS Write Failed");
});

it("shows direct Follow only for a specific active single-entity feed",()=>{
 const entity={id:"team",name:"Racing Bulls",kind:"team",active:true,competitionIDs:[],aliases:[]};
 const global={id:"sports",title:"Sports",kind:"global",entityIDs:[],description:"Global Sports"};
 const named={id:"entity:team",title:"Racing Bulls",kind:"team",entityIDs:[entity.id],description:"Matching Stories"};
 const aggregate={id:"aggregate",title:"Multiple Teams",kind:"team",entityIDs:[entity.id,"other"],description:"Multiple Stories"};
 const state={signedIn:true,viewerDID:"did:plc:experience-direct-follow",items:[],selections:[],selectionsLoading:false,saving:false,saveSelection:async()=>undefined,catalog:{data:{entities:[entity],feeds:[global,named,aggregate]},isPending:false},feed:{hasNextPage:false},isLoading:false,error:null} as unknown as ReturnType<typeof Hooks.useSportsFeed>;
 const feed=spyOn(Hooks,"useSportsFeed").mockReturnValue(state);
 const customize=spyOn(Customize,"SportsCustomize").mockImplementation(()=><></>);
 const prefs=spyOn(Preferences,"useFeedDisplayPreferences").mockReturnValue({preferences:DEFAULT_FEED_DISPLAY_PREFERENCES,setHideSportsScores:()=>{},isLoading:false,isPending:false,error:null} as unknown as ReturnType<typeof Preferences.useFeedDisplayPreferences>);
 restores.push(()=>feed.mockRestore(),()=>customize.mockRestore(),()=>prefs.mockRestore());
 const client=new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0}}});
 restores.push(()=>client.clear());
 const mounted=render(<SportsExperience feedID="sports"/>,{wrapper:({children})=><QueryClientProvider client={client}>{children}</QueryClientProvider>});
 expect(screen.queryByRole("button",{name:"Follow"})).toBeNull();
 mounted.rerender(<SportsExperience feedID="entity:team"/>);
 expect(screen.getByRole("button",{name:"Follow"})).toBeTruthy();
 expect(screen.getByRole("region",{name:"Racing Bulls Overview"})).toBeTruthy();
 mounted.rerender(<SportsExperience feedID="aggregate"/>);
 expect(screen.queryByRole("button",{name:"Follow"})).toBeNull();
 feed.mockReturnValue({...state,catalog:{...state.catalog,data:{...state.catalog.data!,entities:[{...entity,active:false}]}}} as unknown as ReturnType<typeof Hooks.useSportsFeed>);
 mounted.rerender(<SportsExperience feedID="entity:team"/>);
 expect(screen.queryByRole("button",{name:"Follow"})).toBeNull();
});

it("retains catalog derivations during header typing and refreshes them when catalog data changes",()=>{
 const entity={id:"sport",name:"Swimming",kind:"sport",active:true,competitionIDs:[],aliases:["Aquatics"]};
 const definition={id:"entity:sport",title:"Swimming",kind:"sport",entityIDs:[entity.id],description:"Matching Stories"};
 const state={signedIn:false,items:[],selections:[],selectionsLoading:false,saving:false,saveSelection:async()=>undefined,catalog:{data:{entities:[entity],feeds:[definition]},isPending:false},feed:{hasNextPage:false},isLoading:false,error:null} as unknown as ReturnType<typeof Hooks.useSportsFeed>;
 const feed=spyOn(Hooks,"useSportsFeed").mockReturnValue(state);
 const customize=spyOn(Customize,"SportsCustomize").mockImplementation(()=><></>);
 const prefs=spyOn(Preferences,"useFeedDisplayPreferences").mockReturnValue({preferences:DEFAULT_FEED_DISPLAY_PREFERENCES,setHideSportsScores:()=>{},isLoading:false,isPending:false,error:null} as unknown as ReturnType<typeof Preferences.useFeedDisplayPreferences>);
 const observed:SportsPickerFeedDefinition[][]=[];
 const picker=spyOn(Picker,"SportsFeedPicker").mockImplementation(({definitions})=>{observed.push(definitions);return <></>;});
 restores.push(()=>feed.mockRestore(),()=>customize.mockRestore(),()=>prefs.mockRestore(),()=>picker.mockRestore());
 const view=render(<SportsExperience/>);
 const original=observed.at(-1)!;
 expect(original[0]?.searchAliases).toEqual(["Aquatics"]);
 fireEvent.change(screen.getByRole("searchbox"),{target:{value:"Swim"}});
 expect(observed.at(-1)).toBe(original);
 feed.mockReturnValue({...state,catalog:{...state.catalog,data:{...state.catalog.data!,entities:[{...entity,aliases:["Pool"]}]}}} as unknown as ReturnType<typeof Hooks.useSportsFeed>);
 view.rerender(<SportsExperience/>);
 expect(observed.at(-1)).not.toBe(original);
 expect(observed.at(-1)?.[0]?.searchAliases).toEqual(["Pool"]);
});
