# fly.toml app configuration file generated for the-social-wire-dev-appview on 2026-05-21T01:25:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'the-social-wire-dev-appview'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  wait_timeout = '10m0s'

[env]
  ENABLE_THIN_APPVIEW = 'true'
  PORT = '8081'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '1m0s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
