#!/usr/bin/env python3
"""Generate repository-local Go contract data from canonical schema sources."""

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def render():
    """Render deterministic Go constants from canonical sources, without writing."""
    lexicons = {}
    for path in sorted((ROOT / "packages/lexicons").rglob("*.json")):
        if "node_modules" in path.parts:
            continue
        value = json.loads(path.read_text())
        if value.get("lexicon") != 1 or not isinstance(value.get("id"), str):
            continue
        if value["id"] in lexicons:
            raise ValueError("duplicate lexicon " + value["id"])
        lexicons[value["id"]] = value

    def literal(value):
        return json.dumps(value, ensure_ascii=True, separators=(",", ":"))

    bundle = literal(lexicons)
    lex_source = (
        "// Code generated by scripts/go/generate-contracts.py; DO NOT EDIT.\npackage lexicons\n\n// schemaBundle embeds the canonical Lexicon registry; registry.go returns caller-owned copies.\nconst schemaBundle = "
        + json.dumps(bundle)
        + "\n"
    )
    manifest = (ROOT / "packages/spec/endpoint-manifest.json").read_text()
    openapi = (ROOT / "packages/spec/openapi.yaml").read_text()
    spec_source = (
        "// Code generated by scripts/go/generate-contracts.py; DO NOT EDIT.\npackage spec\n\n// endpointManifest preserves the canonical route classifications used by contract lookup.\nconst endpointManifest = "
        + json.dumps(manifest)
        + "\n\n// OpenAPI is the canonical OpenAPI document; parse it with OpenAPIDocument.\nconst OpenAPI = "
        + json.dumps(openapi)
        + "\n\n// OpenAPISHA256 identifies the exact embedded OpenAPI bytes for drift detection.\nconst OpenAPISHA256 = "
        + json.dumps(hashlib.sha256(openapi.encode()).hexdigest())
        + "\n"
    )
    return {
        "lexicons/contracts_generated.go": lex_source,
        "spec/contracts_generated.go": spec_source,
    }


if __name__ == "__main__":
    argument_parser = argparse.ArgumentParser()
    argument_parser.add_argument("--check", action="store_true")
    args = argument_parser.parse_args()
    for name, text in render().items():
        path = ROOT / "packages/go" / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit("Generated contract drift: " + name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
