/// Curated company/listing identities, verified with OpenFIGI v3 mapping on 2026-10-02.
/// These are editorial coverage choices, not a live market-cap ranking. US means
/// the provider's US composite identifier; ADRs and local listings remain distinct.
public enum FinanceCuratedSecurities {
  public static let version = "finance-curated-securities-v2"
  public static let entries: [FinanceReviewedInstrumentMetadata] = [
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BBQCY0"),
      expectedProviderID: "BBG000BBQCY0", expectedSymbol: "AMD", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Advanced Micro Devices"], evidenceURL: "https://www.openfigi.com/id/BBG000BBQCY0", industryIDs: ["semiconductors"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000C0G1D1"),
      expectedProviderID: "BBG000C0G1D1", expectedSymbol: "INTC", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Intel"], evidenceURL: "https://www.openfigi.com/id/BBG000C0G1D1", industryIDs: ["semiconductors"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG00KHY5S69"),
      expectedProviderID: "BBG00KHY5S69", expectedSymbol: "AVGO", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Broadcom"], evidenceURL: "https://www.openfigi.com/id/BBG00KHY5S69", industryIDs: ["semiconductors"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000CGC1X8"),
      expectedProviderID: "BBG000CGC1X8", expectedSymbol: "QCOM", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Qualcomm"], evidenceURL: "https://www.openfigi.com/id/BBG000CGC1X8", industryIDs: ["semiconductors"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BD8ZK0"),
      expectedProviderID: "BBG000BD8ZK0", expectedSymbol: "TSM", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Taiwan Semiconductor", "TSMC"], evidenceURL: "https://www.openfigi.com/id/BBG000BD8ZK0", industryIDs: ["semiconductors"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG01J1GXZF0"),
      expectedProviderID: "BBG01J1GXZF0", expectedSymbol: "ARM", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Arm Holdings"], evidenceURL: "https://www.openfigi.com/id/BBG01J1GXZF0", industryIDs: ["semiconductors"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000K6MRN4"),
      expectedProviderID: "BBG000K6MRN4", expectedSymbol: "ASML", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["ASML"], evidenceURL: "https://www.openfigi.com/id/BBG000K6MRN4", industryIDs: ["semiconductors"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BQLTW7"),
      expectedProviderID: "BBG000BQLTW7", expectedSymbol: "ORCL", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Oracle"], evidenceURL: "https://www.openfigi.com/id/BBG000BQLTW7", industryIDs: ["software"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BB5006"),
      expectedProviderID: "BBG000BB5006", expectedSymbol: "ADBE", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Adobe"], evidenceURL: "https://www.openfigi.com/id/BBG000BB5006", industryIDs: ["software"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BN2DC2"),
      expectedProviderID: "BBG000BN2DC2", expectedSymbol: "CRM", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Salesforce"], evidenceURL: "https://www.openfigi.com/id/BBG000BN2DC2", industryIDs: ["software"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000M1R011"),
      expectedProviderID: "BBG000M1R011", expectedSymbol: "NOW", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["ServiceNow"], evidenceURL: "https://www.openfigi.com/id/BBG000M1R011", industryIDs: ["software"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG008HBD923"),
      expectedProviderID: "BBG008HBD923", expectedSymbol: "SHOP", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Shopify"], evidenceURL: "https://www.openfigi.com/id/BBG008HBD923", industryIDs: ["software"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BDSLD7"),
      expectedProviderID: "BBG000BDSLD7", expectedSymbol: "SAP", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["SAP"], evidenceURL: "https://www.openfigi.com/id/BBG000BDSLD7", industryIDs: ["software"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG0014GJCT9"),
      expectedProviderID: "BBG0014GJCT9", expectedSymbol: "PANW", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Palo Alto Networks"], evidenceURL: "https://www.openfigi.com/id/BBG0014GJCT9", industryIDs: ["software"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG00BLYKS03"),
      expectedProviderID: "BBG00BLYKS03", expectedSymbol: "CRWD", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["CrowdStrike"], evidenceURL: "https://www.openfigi.com/id/BBG00BLYKS03", industryIDs: ["software"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000N7QR55"),
      expectedProviderID: "BBG000N7QR55", expectedSymbol: "PLTR", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Palantir"], evidenceURL: "https://www.openfigi.com/id/BBG000N7QR55", industryIDs: ["software"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG007DHGNJ4"),
      expectedProviderID: "BBG007DHGNJ4", expectedSymbol: "SNOW", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Snowflake"], evidenceURL: "https://www.openfigi.com/id/BBG007DHGNJ4", industryIDs: ["software"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BLNNH6"),
      expectedProviderID: "BBG000BLNNH6", expectedSymbol: "IBM", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["IBM", "International Business Machines"], evidenceURL: "https://www.openfigi.com/id/BBG000BLNNH6", industryIDs: ["hardware"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000C3J3C9"),
      expectedProviderID: "BBG000C3J3C9", expectedSymbol: "CSCO", tradingViewSymbol: nil,
      sectorIDs: ["technology"], aliases: ["Cisco"], evidenceURL: "https://www.openfigi.com/id/BBG000C3J3C9", industryIDs: ["hardware"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BH4R78"),
      expectedProviderID: "BBG000BH4R78", expectedSymbol: "DIS", tradingViewSymbol: nil,
      sectorIDs: ["communications"], aliases: ["Walt Disney", "Disney"], evidenceURL: "https://www.openfigi.com/id/BBG000BH4R78", industryIDs: ["media"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BFT2L4"),
      expectedProviderID: "BBG000BFT2L4", expectedSymbol: "CMCSA", tradingViewSymbol: nil,
      sectorIDs: ["communications"], aliases: ["Comcast"], evidenceURL: "https://www.openfigi.com/id/BBG000BFT2L4", industryIDs: ["media"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BWXBC2"),
      expectedProviderID: "BBG000BWXBC2", expectedSymbol: "WMT", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["Walmart"], evidenceURL: "https://www.openfigi.com/id/BBG000BWXBC2", industryIDs: ["retail"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000F6H8W8"),
      expectedProviderID: "BBG000F6H8W8", expectedSymbol: "COST", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["Costco"], evidenceURL: "https://www.openfigi.com/id/BBG000F6H8W8", industryIDs: ["retail"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BKZB36"),
      expectedProviderID: "BBG000BKZB36", expectedSymbol: "HD", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["Home Depot"], evidenceURL: "https://www.openfigi.com/id/BBG000BKZB36", industryIDs: ["retail"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BNDN65"),
      expectedProviderID: "BBG000BNDN65", expectedSymbol: "LOW", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["Lowe's"], evidenceURL: "https://www.openfigi.com/id/BBG000BNDN65", industryIDs: ["retail"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000H8TVT2"),
      expectedProviderID: "BBG000H8TVT2", expectedSymbol: "TGT", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["Target"], evidenceURL: "https://www.openfigi.com/id/BBG000H8TVT2", industryIDs: ["retail"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000NDYB67"),
      expectedProviderID: "BBG000NDYB67", expectedSymbol: "GM", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["General Motors"], evidenceURL: "https://www.openfigi.com/id/BBG000NDYB67", industryIDs: ["autos"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BQPC32"),
      expectedProviderID: "BBG000BQPC32", expectedSymbol: "F", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["Ford Motor"], evidenceURL: "https://www.openfigi.com/id/BBG000BQPC32", industryIDs: ["autos"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BR2TH3"),
      expectedProviderID: "BBG000BR2TH3", expectedSymbol: "PG", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["Procter & Gamble"], evidenceURL: "https://www.openfigi.com/id/BBG000BR2TH3", industryIDs: ["consumer-products"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BMX289"),
      expectedProviderID: "BBG000BMX289", expectedSymbol: "KO", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["Coca-Cola"], evidenceURL: "https://www.openfigi.com/id/BBG000BMX289", industryIDs: ["consumer-products"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000DH7JK6"),
      expectedProviderID: "BBG000DH7JK6", expectedSymbol: "PEP", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["PepsiCo"], evidenceURL: "https://www.openfigi.com/id/BBG000DH7JK6", industryIDs: ["consumer-products"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000C5HS04"),
      expectedProviderID: "BBG000C5HS04", expectedSymbol: "NKE", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["Nike"], evidenceURL: "https://www.openfigi.com/id/BBG000C5HS04", industryIDs: ["consumer-products"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BNSZP1"),
      expectedProviderID: "BBG000BNSZP1", expectedSymbol: "MCD", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["McDonald's"], evidenceURL: "https://www.openfigi.com/id/BBG000BNSZP1", industryIDs: ["restaurants"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000CTQBF3"),
      expectedProviderID: "BBG000CTQBF3", expectedSymbol: "SBUX", tradingViewSymbol: nil,
      sectorIDs: ["consumer"], aliases: ["Starbucks"], evidenceURL: "https://www.openfigi.com/id/BBG000CTQBF3", industryIDs: ["restaurants"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG0025Y4RY4"),
      expectedProviderID: "BBG0025Y4RY4", expectedSymbol: "ABBV", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["AbbVie"], evidenceURL: "https://www.openfigi.com/id/BBG0025Y4RY4", industryIDs: ["pharma"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BPD168"),
      expectedProviderID: "BBG000BPD168", expectedSymbol: "MRK", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["Merck"], evidenceURL: "https://www.openfigi.com/id/BBG000BPD168", industryIDs: ["pharma"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000DQLV23"),
      expectedProviderID: "BBG000DQLV23", expectedSymbol: "BMY", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["Bristol Myers Squibb"], evidenceURL: "https://www.openfigi.com/id/BBG000DQLV23", industryIDs: ["pharma"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BQBKR3"),
      expectedProviderID: "BBG000BQBKR3", expectedSymbol: "NVO", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["Novo Nordisk"], evidenceURL: "https://www.openfigi.com/id/BBG000BQBKR3", industryIDs: ["pharma"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000D3MHB4"),
      expectedProviderID: "BBG000D3MHB4", expectedSymbol: "AZN", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["AstraZeneca"], evidenceURL: "https://www.openfigi.com/id/BBG000D3MHB4", industryIDs: ["pharma"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000LYF3S8"),
      expectedProviderID: "BBG000LYF3S8", expectedSymbol: "NVS", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["Novartis"], evidenceURL: "https://www.openfigi.com/id/BBG000LYF3S8", industryIDs: ["pharma"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BBS2Y0"),
      expectedProviderID: "BBG000BBS2Y0", expectedSymbol: "AMGN", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["Amgen"], evidenceURL: "https://www.openfigi.com/id/BBG000BBS2Y0", industryIDs: ["biotech"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000CKGBP2"),
      expectedProviderID: "BBG000CKGBP2", expectedSymbol: "GILD", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["Gilead Sciences", "Gilead"], evidenceURL: "https://www.openfigi.com/id/BBG000CKGBP2", industryIDs: ["biotech"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BNWG87"),
      expectedProviderID: "BBG000BNWG87", expectedSymbol: "MDT", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["Medtronic"], evidenceURL: "https://www.openfigi.com/id/BBG000BNWG87", industryIDs: ["medical-devices"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000B9ZXB4"),
      expectedProviderID: "BBG000B9ZXB4", expectedSymbol: "ABT", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["Abbott Laboratories", "Abbott"], evidenceURL: "https://www.openfigi.com/id/BBG000B9ZXB4", industryIDs: ["medical-devices"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BJPDZ1"),
      expectedProviderID: "BBG000BJPDZ1", expectedSymbol: "ISRG", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["Intuitive Surgical"], evidenceURL: "https://www.openfigi.com/id/BBG000BJPDZ1", industryIDs: ["medical-devices"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BVDLH9"),
      expectedProviderID: "BBG000BVDLH9", expectedSymbol: "TMO", tradingViewSymbol: nil,
      sectorIDs: ["healthcare"], aliases: ["Thermo Fisher Scientific"], evidenceURL: "https://www.openfigi.com/id/BBG000BVDLH9", industryIDs: ["medical-devices"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000DMBXR2"),
      expectedProviderID: "BBG000DMBXR2", expectedSymbol: "JPM", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["JPMorgan Chase", "JPMorgan"], evidenceURL: "https://www.openfigi.com/id/BBG000DMBXR2", industryIDs: ["banks"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BCTLF6"),
      expectedProviderID: "BBG000BCTLF6", expectedSymbol: "BAC", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["Bank of America"], evidenceURL: "https://www.openfigi.com/id/BBG000BCTLF6", industryIDs: ["banks"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BWQFY7"),
      expectedProviderID: "BBG000BWQFY7", expectedSymbol: "WFC", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["Wells Fargo"], evidenceURL: "https://www.openfigi.com/id/BBG000BWQFY7", industryIDs: ["banks"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000FY4S11"),
      expectedProviderID: "BBG000FY4S11", expectedSymbol: "C", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["Citigroup"], evidenceURL: "https://www.openfigi.com/id/BBG000FY4S11", industryIDs: ["banks"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000C6CFJ5"),
      expectedProviderID: "BBG000C6CFJ5", expectedSymbol: "GS", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["Goldman Sachs"], evidenceURL: "https://www.openfigi.com/id/BBG000C6CFJ5", industryIDs: ["banks"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BLZRJ2"),
      expectedProviderID: "BBG000BLZRJ2", expectedSymbol: "MS", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["Morgan Stanley"], evidenceURL: "https://www.openfigi.com/id/BBG000BLZRJ2", industryIDs: ["banks"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG007DJM539"),
      expectedProviderID: "BBG007DJM539", expectedSymbol: "UBS", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["UBS Group"], evidenceURL: "https://www.openfigi.com/id/BBG007DJM539", industryIDs: ["banks"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000PSKYX7"),
      expectedProviderID: "BBG000PSKYX7", expectedSymbol: "V", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["Visa"], evidenceURL: "https://www.openfigi.com/id/BBG000PSKYX7", industryIDs: ["payments"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000F1ZSQ2"),
      expectedProviderID: "BBG000F1ZSQ2", expectedSymbol: "MA", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["Mastercard"], evidenceURL: "https://www.openfigi.com/id/BBG000F1ZSQ2", industryIDs: ["payments"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BCQZS4"),
      expectedProviderID: "BBG000BCQZS4", expectedSymbol: "AXP", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["American Express"], evidenceURL: "https://www.openfigi.com/id/BBG000BCQZS4", industryIDs: ["payments"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG0077VNXV6"),
      expectedProviderID: "BBG0077VNXV6", expectedSymbol: "PYPL", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["PayPal"], evidenceURL: "https://www.openfigi.com/id/BBG0077VNXV6", industryIDs: ["payments"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BR14K5"),
      expectedProviderID: "BBG000BR14K5", expectedSymbol: "CB", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["Chubb"], evidenceURL: "https://www.openfigi.com/id/BBG000BR14K5", industryIDs: ["insurance"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BR37X2"),
      expectedProviderID: "BBG000BR37X2", expectedSymbol: "PGR", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["Progressive Corp"], evidenceURL: "https://www.openfigi.com/id/BBG000BR37X2", industryIDs: ["insurance"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BVMGF2"),
      expectedProviderID: "BBG000BVMGF2", expectedSymbol: "ALL", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["Allstate"], evidenceURL: "https://www.openfigi.com/id/BBG000BVMGF2", industryIDs: ["insurance"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG01PSW2WN4"),
      expectedProviderID: "BBG01PSW2WN4", expectedSymbol: "BLK", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["BlackRock"], evidenceURL: "https://www.openfigi.com/id/BBG01PSW2WN4", industryIDs: ["asset-management"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BSLZY7"),
      expectedProviderID: "BBG000BSLZY7", expectedSymbol: "SCHW", tradingViewSymbol: nil,
      sectorIDs: ["financials"], aliases: ["Charles Schwab"], evidenceURL: "https://www.openfigi.com/id/BBG000BSLZY7", industryIDs: ["asset-management"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG023CY9MM1"),
      expectedProviderID: "BBG023CY9MM1", expectedSymbol: "XOM", tradingViewSymbol: nil,
      sectorIDs: ["energy"], aliases: ["Exxon Mobil", "ExxonMobil"], evidenceURL: "https://www.openfigi.com/id/BBG023CY9MM1", industryIDs: ["oil-gas"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000K4ND22"),
      expectedProviderID: "BBG000K4ND22", expectedSymbol: "CVX", tradingViewSymbol: nil,
      sectorIDs: ["energy"], aliases: ["Chevron"], evidenceURL: "https://www.openfigi.com/id/BBG000K4ND22", industryIDs: ["oil-gas"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG0147BN6G2"),
      expectedProviderID: "BBG0147BN6G2", expectedSymbol: "SHEL", tradingViewSymbol: nil,
      sectorIDs: ["energy"], aliases: ["Shell"], evidenceURL: "https://www.openfigi.com/id/BBG0147BN6G2", industryIDs: ["oil-gas"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BT4FC2"),
      expectedProviderID: "BBG000BT4FC2", expectedSymbol: "BP", tradingViewSymbol: nil,
      sectorIDs: ["energy"], aliases: ["BP"], evidenceURL: "https://www.openfigi.com/id/BBG000BT4FC2", industryIDs: ["oil-gas"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000JLVJ97"),
      expectedProviderID: "BBG000JLVJ97", expectedSymbol: "TTE", tradingViewSymbol: nil,
      sectorIDs: ["energy"], aliases: ["TotalEnergies"], evidenceURL: "https://www.openfigi.com/id/BBG000JLVJ97", industryIDs: ["oil-gas"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BQQH30"),
      expectedProviderID: "BBG000BQQH30", expectedSymbol: "COP", tradingViewSymbol: nil,
      sectorIDs: ["energy"], aliases: ["ConocoPhillips"], evidenceURL: "https://www.openfigi.com/id/BBG000BQQH30", industryIDs: ["oil-gas"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BT41Q8"),
      expectedProviderID: "BBG000BT41Q8", expectedSymbol: "SLB", tradingViewSymbol: nil,
      sectorIDs: ["energy"], aliases: ["Schlumberger"], evidenceURL: "https://www.openfigi.com/id/BBG000BT41Q8", industryIDs: ["oil-gas"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BZ9223"),
      expectedProviderID: "BBG000BZ9223", expectedSymbol: "EOG", tradingViewSymbol: nil,
      sectorIDs: ["energy"], aliases: ["EOG Resources"], evidenceURL: "https://www.openfigi.com/id/BBG000BZ9223", industryIDs: ["oil-gas"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG01FND0CC1"),
      expectedProviderID: "BBG01FND0CC1", expectedSymbol: "LIN", tradingViewSymbol: nil,
      sectorIDs: ["materials"], aliases: ["Linde"], evidenceURL: "https://www.openfigi.com/id/BBG01FND0CC1", industryIDs: []),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BD5NZ4"),
      expectedProviderID: "BBG000BD5NZ4", expectedSymbol: "BHP", tradingViewSymbol: nil,
      sectorIDs: ["materials"], aliases: ["BHP Group"], evidenceURL: "https://www.openfigi.com/id/BBG000BD5NZ4", industryIDs: ["mining"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000FD28T3"),
      expectedProviderID: "BBG000FD28T3", expectedSymbol: "RIO", tradingViewSymbol: nil,
      sectorIDs: ["materials"], aliases: ["Rio Tinto"], evidenceURL: "https://www.openfigi.com/id/BBG000FD28T3", industryIDs: ["mining"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BJDB15"),
      expectedProviderID: "BBG000BJDB15", expectedSymbol: "FCX", tradingViewSymbol: nil,
      sectorIDs: ["materials"], aliases: ["Freeport-McMoRan"], evidenceURL: "https://www.openfigi.com/id/BBG000BJDB15", industryIDs: ["mining"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BPWXK1"),
      expectedProviderID: "BBG000BPWXK1", expectedSymbol: "NEM", tradingViewSymbol: nil,
      sectorIDs: ["materials"], aliases: ["Newmont"], evidenceURL: "https://www.openfigi.com/id/BBG000BPWXK1", industryIDs: ["mining"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BF0K17"),
      expectedProviderID: "BBG000BF0K17", expectedSymbol: "CAT", tradingViewSymbol: nil,
      sectorIDs: ["industrials"], aliases: ["Caterpillar"], evidenceURL: "https://www.openfigi.com/id/BBG000BF0K17", industryIDs: ["manufacturing"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BH1NH9"),
      expectedProviderID: "BBG000BH1NH9", expectedSymbol: "DE", tradingViewSymbol: nil,
      sectorIDs: ["industrials"], aliases: ["Deere", "John Deere"], evidenceURL: "https://www.openfigi.com/id/BBG000BH1NH9", industryIDs: ["manufacturing"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BK6MB5"),
      expectedProviderID: "BBG000BK6MB5", expectedSymbol: "GE", tradingViewSymbol: nil,
      sectorIDs: ["industrials"], aliases: ["GE Aerospace"], evidenceURL: "https://www.openfigi.com/id/BBG000BK6MB5", industryIDs: ["manufacturing"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000H556T9"),
      expectedProviderID: "BBG000H556T9", expectedSymbol: "HON", tradingViewSymbol: nil,
      sectorIDs: ["industrials"], aliases: ["Honeywell"], evidenceURL: "https://www.openfigi.com/id/BBG000H556T9", industryIDs: ["manufacturing"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BJ3PD2"),
      expectedProviderID: "BBG000BJ3PD2", expectedSymbol: "ETN", tradingViewSymbol: nil,
      sectorIDs: ["industrials"], aliases: ["Eaton"], evidenceURL: "https://www.openfigi.com/id/BBG000BJ3PD2", industryIDs: ["manufacturing"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BW8S60"),
      expectedProviderID: "BBG000BW8S60", expectedSymbol: "RTX", tradingViewSymbol: nil,
      sectorIDs: ["industrials"], aliases: ["RTX Corp", "Raytheon"], evidenceURL: "https://www.openfigi.com/id/BBG000BW8S60", industryIDs: ["aerospace-defense"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000C1BW00"),
      expectedProviderID: "BBG000C1BW00", expectedSymbol: "LMT", tradingViewSymbol: nil,
      sectorIDs: ["industrials"], aliases: ["Lockheed Martin"], evidenceURL: "https://www.openfigi.com/id/BBG000C1BW00", industryIDs: ["aerospace-defense"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BCSST7"),
      expectedProviderID: "BBG000BCSST7", expectedSymbol: "BA", tradingViewSymbol: nil,
      sectorIDs: ["industrials"], aliases: ["Boeing"], evidenceURL: "https://www.openfigi.com/id/BBG000BCSST7", industryIDs: ["aerospace-defense"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000L9CV04"),
      expectedProviderID: "BBG000L9CV04", expectedSymbol: "UPS", tradingViewSymbol: nil,
      sectorIDs: ["industrials"], aliases: ["United Parcel Service"], evidenceURL: "https://www.openfigi.com/id/BBG000L9CV04", industryIDs: ["transportation"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BW3299"),
      expectedProviderID: "BBG000BW3299", expectedSymbol: "UNP", tradingViewSymbol: nil,
      sectorIDs: ["industrials"], aliases: ["Union Pacific"], evidenceURL: "https://www.openfigi.com/id/BBG000BW3299", industryIDs: ["transportation"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BSJK37"),
      expectedProviderID: "BBG000BSJK37", expectedSymbol: "T", tradingViewSymbol: nil,
      sectorIDs: ["communications"], aliases: ["AT&T"], evidenceURL: "https://www.openfigi.com/id/BBG000BSJK37", industryIDs: ["telecom"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000HS77T5"),
      expectedProviderID: "BBG000HS77T5", expectedSymbol: "VZ", tradingViewSymbol: nil,
      sectorIDs: ["communications"], aliases: ["Verizon"], evidenceURL: "https://www.openfigi.com/id/BBG000HS77T5", industryIDs: ["telecom"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000NDV1D4"),
      expectedProviderID: "BBG000NDV1D4", expectedSymbol: "TMUS", tradingViewSymbol: nil,
      sectorIDs: ["communications"], aliases: ["T-Mobile US"], evidenceURL: "https://www.openfigi.com/id/BBG000NDV1D4", industryIDs: ["telecom"]),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BJSBJ0"),
      expectedProviderID: "BBG000BJSBJ0", expectedSymbol: "NEE", tradingViewSymbol: nil,
      sectorIDs: ["utilities"], aliases: ["NextEra Energy"], evidenceURL: "https://www.openfigi.com/id/BBG000BJSBJ0", industryIDs: []),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BHGDH5"),
      expectedProviderID: "BBG000BHGDH5", expectedSymbol: "DUK", tradingViewSymbol: nil,
      sectorIDs: ["utilities"], aliases: ["Duke Energy"], evidenceURL: "https://www.openfigi.com/id/BBG000BHGDH5", industryIDs: []),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000BT9DW0"),
      expectedProviderID: "BBG000BT9DW0", expectedSymbol: "SO", tradingViewSymbol: nil,
      sectorIDs: ["utilities"], aliases: ["Southern Co"], evidenceURL: "https://www.openfigi.com/id/BBG000BT9DW0", industryIDs: []),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000B9Z0J8"),
      expectedProviderID: "BBG000B9Z0J8", expectedSymbol: "PLD", tradingViewSymbol: nil,
      sectorIDs: ["real-estate"], aliases: ["Prologis"], evidenceURL: "https://www.openfigi.com/id/BBG000B9Z0J8", industryIDs: []),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000B9XYV2"),
      expectedProviderID: "BBG000B9XYV2", expectedSymbol: "AMT", tradingViewSymbol: nil,
      sectorIDs: ["real-estate"], aliases: ["American Tower"], evidenceURL: "https://www.openfigi.com/id/BBG000B9XYV2", industryIDs: []),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000MBDGM6"),
      expectedProviderID: "BBG000MBDGM6", expectedSymbol: "EQIX", tradingViewSymbol: nil,
      sectorIDs: ["real-estate"], aliases: ["Equinix"], evidenceURL: "https://www.openfigi.com/id/BBG000MBDGM6", industryIDs: []),
    .init(instrumentID: FinanceIdentity.instrumentID(provider: "openfigi", nativeID: "BBG000DHPN63"),
      expectedProviderID: "BBG000DHPN63", expectedSymbol: "O", tradingViewSymbol: nil,
      sectorIDs: ["real-estate"], aliases: ["Realty Income"], evidenceURL: "https://www.openfigi.com/id/BBG000DHPN63", industryIDs: []),
  ]
}
